### ISSUE TITLE
Error: Invalid layer

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#4026] opened 2017-03-08 02:29 UTC
I am getting this error when running raster earthquake on vector population and vector aggregation.

```
In file "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\impact_function\impact_function.py", line 1081, in run self._run()
In file "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\utilities\profiling.py", line 93, in with_profiling ret = fn(*args, **kwargs)
In file "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\impact_function\impact_function.py", line 1245, in _run self.gis_overlay_analysis()
In file "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\utilities\profiling.py", line 93, in with_profiling ret = fn(*args, **kwargs)
In file "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\impact_function\impact_function.py", line 1344, in gis_overlay_analysis self.hazard_preparation()
In file "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\utilities\profiling.py", line 93, in with_profiling ret = fn(*args, **kwargs)
In file "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\impact_function\impact_function.py", line 1665, in hazard_preparation self.hazard = clip_by_extent(self.hazard, extent)
In file "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\utilities\profiling.py", line 93, in with_profiling ret = fn(*args, **kwargs)
In file "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\gis\raster\clip_bounding_box.py", line 86, in clip_by_extent check_layer(clipped)
In file "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\gis\sanity_check.py", line 70, in check_layer raise InvalidLayerError(tr('The layer is invalid.'))
```

**Comment by Charlotte-Morgan** [comment] 2017-03-08 02:30
'''
			
2017-03-08T09:27:36	0	ANALYSIS : The impact function is starting.
2017-03-08T09:27:37	0	Datastore : C:/AIFDR/AIFDR II - SDA/temp/EarthquakeRasterOnPopulationPolygon_08March2017_09h27-37.009000
2017-03-08T09:27:37	0	ANALYSIS : Aggregation preparation
2017-03-08T09:27:37	0	aggregation: provided: True
2017-03-08T09:27:37	0	aggregation: Cleaning the aggregation layer
2017-03-08T09:27:37	0	Features which have been removed from aggregation : 0
2017-03-08T09:27:37	0	We add an ID column in aggregation
2017-03-08T09:27:37	0	Fields which have been renamed from aggregation :
2017-03-08T09:27:37	0	KEC_NAME -> aggregation_name
2017-03-08T09:27:37	0	Fields which have been removed from aggregation : KEC_NAME KAB_NAME
2017-03-08T09:27:37	0	aggregation: Aggregation layer already in exposure CRS
2017-03-08T09:27:37	0	female_ratio_field is not in the detected in the aggregation layer AND female_count_field is detected in the exposure layer. We do nothing in this step.
2017-03-08T09:27:37	0	youth_ratio_field is not in the detected in the aggregation layer AND youth_count_field is detected in the exposure layer. We do nothing in this step.
2017-03-08T09:27:37	0	adult_ratio_field is not in the detected in the aggregation layer AND adult_count_field is detected in the exposure layer. We do nothing in this step.
2017-03-08T09:27:37	0	elderly_ratio_field is not in the detected in the aggregation layer AND elderly_count_field is detected in the exposure layer. We do nothing in this step.
2017-03-08T09:27:37	0	aggregation: Convert the aggregation layer to the analysis layer
2017-03-08T09:27:37	0	Starting a GIS overlay analysis
2017-03-08T09:27:37	0	ANALYSIS : Hazard preparation
2017-03-08T09:27:37	0	hazard: use_same_projection: True
2017-03-08T09:27:37	0	hazard: Clip raster by analysis bounding box
2017-03-08T09:27:37	0	The impact function could not run because of a bug.
2017-03-08T09:27:41	0	****Problem
			
			    The following problem(s) were encountered whilst running the analysis.
			
			 - InvalidLayerError
			
			****Suggestion
			
			    You can try the following to resolve the issue:
			
			 - The layer is invalid.
			
			*****Details
			
			    These additional details were reported when the problem occurred.
			
			 - The layer is invalid.
			
			*****Diagnostics
			
			 1. In file "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\impact_function\impact_function.py", line 1081, in run self._run()
			 2. In file "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\utilities\profiling.py", line 93, in with_profiling ret = fn(*args, **kwargs)
			 3. In file "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\impact_function\impact_function.py", line 1245, in _run self.gis_overlay_analysis()
			 4. In file "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\utilities\profiling.py", line 93, in with_profiling ret = fn(*args, **kwargs)
			 5. In file "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\impact_function\impact_function.py", line 1344, in gis_overlay_analysis self.hazard_preparation()
			 6. In file "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\utilities\profiling.py", line 93, in with_profiling ret = fn(*args, **kwargs)
			 7. In file "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\impact_function\impact_function.py", line 1665, in hazard_preparation self.hazard = clip_by_extent(self.hazard, extent)
			 8. In file "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\utilities\profiling.py", line 93, in with_profiling ret = fn(*args, **kwargs)
			 9. In file "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\gis\raster\clip_bounding_box.py", line 86, in clip_by_extent check_layer(clipped)
			 10. In file "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\gis\sanity_check.py", line 70, in check_layer raise InvalidLayerError(tr('The layer is invalid.'))
```

**Comment by Charlotte-Morgan** [comment] 2017-03-08 04:58
here is the data - I am using fields in the data for total population, female population, adult population, youth population and elderly population.

**Comment by Charlotte-Morgan** [comment] 2017-03-08 04:58
![image](https://cloud.githubusercontent.com/assets/5743135/23690734/85c96c84-03f6-11e7-9d1d-8f52f0d47bcc.png)

**Comment by Charlotte-Morgan** [comment] 2017-03-08 04:58
[Jkt_SubDistrictPopulation.zip](https://github.com/inasafe/inasafe/files/826680/Jkt_SubDistrictPopulation.zip)

**Comment by ismailsunni** [comment] 2017-03-08 07:17
Hi @Charlotte-Morgan 
I tried to use your population data and standard test data for hazard and aggregation. It runs fine in my machine
<img width="1432" alt="screen shot 2017-03-08 at 14 15 40" src="https://cloud.githubusercontent.com/assets/1421861/23693956/d27454be-0409-11e7-8e68-39eddc7886d1.png">

Do you have any comment @Gustry ?

**Comment by Gustry** [comment] 2017-03-08 07:50
Reading the logs, the problem is when we combine the hazard and the aggregation. Can we have both layers ? Not only the aggregation.

**Comment by Charlotte-Morgan** [comment] 2017-03-08 09:43
[JakartaEQ_DoNotDistribute.zip](https://github.com/inasafe/inasafe/files/827183/JakartaEQ_DoNotDistribute.zip)

@Gustry - here is the file. This should not be distributed or used for anything but bug fixing this ticket.
Thanks

**Comment by Gustry** [comment] 2017-03-08 16:29
GDAL Info
```
etienne@:~/dev/inasafe/inasafe (clip_raster_by_extent *) $ gdalinfo /Users/etienne/Downloads/JakartaEQ_DoNotDistribute/SundaInSlab1-nearest.tif
Driver: GTiff/GeoTIFF
Files: /Users/etienne/Downloads/JakartaEQ_DoNotDistribute/SundaInSlab1-nearest.tif
Size is 121, 120
Coordinate System is:
GEOGCS["WGS 84",
    DATUM["WGS_1984",
        SPHEROID["WGS 84",6378137,298.257223563,
            AUTHORITY["EPSG","7030"]],
        AUTHORITY["EPSG","6326"]],
    PRIMEM["Greenwich",0],
    UNIT["degree",0.0174532925199433],
    AUTHORITY["EPSG","4326"]]
Origin = (104.203599999999994,-7.702500000000000)
Pixel Size = (0.024793388429752,0.024850000000000)
Metadata:
  AREA_OR_POINT=Area
Image Structure Metadata:
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  ( 104.2036000,  -7.7025000) (104d12'12.96"E,  7d42' 9.00"S)
Lower Left  ( 104.2036000,  -4.7205000) (104d12'12.96"E,  4d43'13.80"S)
Upper Right ( 107.2036000,  -7.7025000) (107d12'12.96"E,  7d42' 9.00"S)
Lower Right ( 107.2036000,  -4.7205000) (107d12'12.96"E,  4d43'13.80"S)
Center      ( 105.7036000,  -6.2115000) (105d42'12.96"E,  6d12'41.40"S)
Band 1 Block=121x67 Type=Byte, ColorInterp=Gray
  NoData Value=200
```

When we try to clip with GDAL command line with gdal_translate : 
```
gdal_translate -projwin 104.2036 -4.7205 107.20699853 -7.69907705456 /Users/etienne/Downloads/JakartaEQ_DoNotDistribute/SundaInSlab1-nearest.tif /tmp/output.tif
Input file size is 121, 120
ERROR 1: Error: Computed -srcwin 0 120 121 -120 has negative width and/or height.
```

As QGIS is using GDAL command line in the background, it's also failing to use QGIS UI to clip the raster with the same error.
I'm a little bit clueless for now. I can make a hack if this processing step is failing.

**Comment by Gustry** [comment] 2017-03-08 17:06
Ok, I got it : 
The raster is south up and not north up.
From GDAL Info : 
```
Upper Left  ( 104.2036000,  -7.7025000)
Lower Left  ( 104.2036000,  -4.7205000)
Upper Right ( 107.2036000,  -7.7025000)
Lower Right ( 107.2036000,  -4.7205000)
```

I can make another fix.

**Comment by Gustry** [comment] 2017-03-08 20:25
You made a patch for : 
* managing this upside down raster. I don't if it's very common to have this kind of raster and I should I dive deeper in the GIS analysis with this kind of use case.
* be able to skip the clip_raster_by_extent if the algorithm goes wrong. This step is only here to speedup the analysis. I don't stop the analysis if the algorithm goes wrong. The raster will be clip later when it will become a vector layer.

**Comment by Charlotte-Morgan** [comment] 2017-03-09 06:09
hi @Gustry - this raster was produced by shake to grid converter. Can you please check the problem is not with the converter?

**Comment by Gustry** [comment] 2017-03-09 07:24
Thanks Charlotte. I could fix the analysis to not raise an error.
@myarjunar is now looking with the shakemap converter. It seems we have a bug depending on south or north hemisphere.

**Comment by Charlotte-Morgan** [comment] 2017-03-09 10:00
hi @Gustry - I am getting this error again.
```
In file "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\impact_function\impact_function.py", line 1076, in run self._run()
In file "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\utilities\profiling.py", line 93, in with_profiling ret = fn(*args, **kwargs)
In file "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\impact_function\impact_function.py", line 1240, in _run self.gis_overlay_analysis()
In file "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\utilities\profiling.py", line 93, in with_profiling ret = fn(*args, **kwargs)
In file "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\impact_function\impact_function.py", line 1342, in gis_overlay_analysis self.hazard_preparation()
In file "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\utilities\profiling.py", line 93, in with_profiling ret = fn(*args, **kwargs)
In file "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\impact_function\impact_function.py", line 1663, in hazard_preparation self.hazard = clip_by_extent(self.hazard, extent)
In file "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\utilities\profiling.py", line 93, in with_profiling ret = fn(*args, **kwargs)
In file "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\gis\raster\clip_bounding_box.py", line 86, in clip_by_extent check_layer(clipped)
In file "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\gis\sanity_check.py", line 70, in check_layer raise InvalidLayerError(tr('The layer is invalid.'))
```

**Comment by Charlotte-Morgan** [comment] 2017-03-09 10:01
This time I am using Raster EQ, Vector pop and vector aggregation with fields for ratios

**Comment by Gustry** [comment] 2017-03-09 10:02
With develop again ?
Hum how is it possible :D

**Comment by Charlotte-Morgan** [comment] 2017-03-09 10:10
ok - more clean code pulling - now its a type error :)

**Comment by Charlotte-Morgan** [comment] 2017-03-09 10:10
```
In file "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\impact_function\impact_function.py", line 1076, in run self._run()
In file "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\utilities\profiling.py", line 93, in with_profiling ret = fn(*args, **kwargs)
In file "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\impact_function\impact_function.py", line 1240, in _run self.gis_overlay_analysis()
In file "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\utilities\profiling.py", line 93, in with_profiling ret = fn(*args, **kwargs)
In file "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\impact_function\impact_function.py", line 1342, in gis_overlay_analysis self.hazard_preparation()
In file "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\utilities\profiling.py", line 93, in with_profiling ret = fn(*args, **kwargs)
In file "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\impact_function\impact_function.py", line 1663, in hazard_preparation self.hazard = clip_by_extent(self.hazard, extent)
In file "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\utilities\profiling.py", line 93, in with_profiling ret = fn(*args, **kwargs)
In file "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\gis\raster\clip_bounding_box.py", line 95, in clip_by_extent result = processing.runalg("gdalogr:cliprasterbyextent", parameters)
In file "C:/PROGRA~1/QGIS2~1.14/apps/qgis-ltr/./python/plugins\processing\tools\general.py", line 71, in runalg alg = Processing.runAlgorithm(algOrName, None, *args, **kwargs)
In file "C:/PROGRA~1/QGIS2~1.14/apps/qgis-ltr/./python/plugins\processing\core\Processing.py", line 268, in runAlgorithm if isinstance(algOrName, GeoAlgorithm):
```

**Comment by Gustry** [comment] 2017-03-09 15:43
Ah ok, so no more invalid layer ?

I guess you are missing some parts of the log, you should have many sections : problems, suggestions, details and diagnostics. The type error is missing from the logs.

**Comment by Gustry** [comment] 2017-03-10 10:07
You shouldn't get any problem with develop again.
But I would still appreciate if you can copy/paste your full logs with this analysis, even if the analysis can run without any problems.

**Comment by Gustry** [comment] 2017-03-27 20:17
I'm closing this ticket. Feel free to reopen if needed.

**Closed by Gustry** 2017-03-27 20:17 UTC
Labels: Bug, Candidate for closing
