### ISSUE TITLE
Zero rows in detailed agregate result on Popoulation exposure

### ISSUE THREAD

**Issue by ivanbusthomi** [inasafe/inasafe#3787] opened 2017-02-07 09:47 UTC
### Problem
When I tried running volcano and tsunami hazard on population exposure using aggregation, I got zero rows for each village that doesn't have affected people
![image](https://cloud.githubusercontent.com/assets/7351977/22685935/dc96748e-ed54-11e6-9532-420bb5c85baf.png)

### Expected Behaviour
Columns and rows containing only 0 or "No data" values are excluded from the tables.

### Environment
* InaSAFE : 4.0 develop
* QGIS : 2.14.10
* OS : Windows
* Data used : Nagekeo and Ambon
  * Exposure : Population
  * Hazard : Volcano and Tsunami
  * Aggregation : Villages

### Proposed Solution
make it happy :)

---
cc: @Gustry @ismailsunni @timlinux @Charlotte-Morgan @samnawi @felix-yew

**Comment by lucernae** [comment] 2017-02-10 09:19
Fix is on the way

**Comment by lucernae** [comment] 2017-02-13 11:09
Try it again @ivanbusthomi and close this ticket if it is solved.

**Comment by ivanbusthomi** [comment] 2017-02-15 16:13
Hi @lucernae , sorry for late response.
I tried using volcano hazard on landcover, population and buildings with aggregation. In the report for buildings and landcover, there are no zero rows or columns appear in aggregation result. But in population, I got no aggregation result section. Only the estimated summary, action checklist, notes and assumption, and analysis details sections.

**Comment by lucernae** [comment] 2017-02-16 07:42
Hi @ivanbusthomi, It will not show up if all the aggregation result is empty. Perhaps you could use a bigger dataset? All population calculation is using displaced with ratio 1%, so you have to at least have 100 people affected?
If this is a problem, maybe we should keep the section but tell the user that it is empty.

**Comment by Gustry** [comment] 2017-02-16 07:49
And the displacement rate is 0 for some hazards.

> If this is a problem, maybe we should keep the section but tell the user that it is empty.

I though we said we should display a message @lucernae ? At least to show them that's not a bug.

**Comment by ivanbusthomi** [comment] 2017-02-23 05:17
Hi mas @lucernae , and @Gustry 
So I tried using bigger population dataset from Worldpop, and this is how the data look like,
![image](https://cloud.githubusercontent.com/assets/7351977/23245358/658c063a-f9be-11e6-9760-29fac625b305.png)

---
 and this is the result table that I got. there is still no aggregated result.
![image](https://cloud.githubusercontent.com/assets/7351977/23245366/776f7404-f9be-11e6-82d6-ee9bfe83395e.png)

Looking at the image above, I believe that there should be some aggregation areas that are not empty. And the total affected people are 3900. 
I tried opening the attribute table, this is what I got.
![image](https://cloud.githubusercontent.com/assets/7351977/23245774/b9675414-f9c1-11e6-8c47-3c492bc61de2.png)



from the attribute table, we can see that there is affected people in WOLOPOGO. **Please CMIIW**, but my understanding is that value should be shown in the report even though the displaced people is 0. 

cc mas @samnawi and mas @felix-yew

**Comment by Gustry** [comment] 2017-02-23 06:45
Hum, yes we missed it now

**Comment by ivanbusthomi** [comment] 2017-02-23 08:58
Hi @Gustry and @lucernae,
We have discussed this and agreed that it may be OK to not shows them because there are no displaced people, because if we show them it will show zero column like this.
![image](https://cloud.githubusercontent.com/assets/7351977/23251368/a0cf7c74-f9df-11e6-9ee6-bb34532afa03.png)

> I though we said we should display a message @lucernae ? At least to show them that's not a bug.

I agree with what @Gustry said. What we suggest is that we add some text in the notes and assumption for analysis on population saying something like `if the displacement rates are 0%, no minimum needs are calculated and shown.` 
It would also mean that this table will be hidden.

![image](https://cloud.githubusercontent.com/assets/7351977/23251453/ec54930a-f9df-11e6-9317-d13f77f96b31.png)

CC @Charlotte-Morgan

**Comment by lucernae** [comment] 2017-02-23 09:08
@ivanbusthomi another note, @Gustry and I think that we should show "Total displaced" column Aggregation minimum needs, gender, and age. Should we replace Total population with total displaced or just have both in the table (we might want to change Total population to Total affected population to be clear).

**Comment by ivanbusthomi** [comment] 2017-02-23 09:12
yeah, sorry, I forgot to add that in my comment above.
we also discussed about that too, that if the table are shown it should be total displaced instead, because the other column is about displaced people, not affected people (which I believe the total population column that I showed refers to total affected population, right?). That's why I got misunderstood that the table are not shown is a bug.

**Comment by lucernae** [comment] 2017-02-23 09:28
Ok. thank's for the clarification.

**Comment by lucernae** [comment] 2017-02-23 13:55
I added extra messages:

If total displaced count 0:
for minimum needs
<img width="1183" alt="screen shot 2017-02-23 at 18 47 03" src="https://cloud.githubusercontent.com/assets/831865/23258314/3c41d048-f9fa-11e6-8667-2026a28e7857.png">

for aggregation postprocessors
<img width="1187" alt="screen shot 2017-02-23 at 18 57 30" src="https://cloud.githubusercontent.com/assets/831865/23258317/3dc6c23e-f9fa-11e6-89c1-d75e233b060d.png">

**Comment by lucernae** [comment] 2017-02-23 14:01
changed column header to "Total displaced population" and add "male displaced count"
<img width="1205" alt="screen shot 2017-02-23 at 20 58 13" src="https://cloud.githubusercontent.com/assets/831865/23261880/0d2cb5d2-fa0b-11e6-8c44-0e5be1c21f67.png">

**Comment by timlinux** [comment] 2017-02-27 09:18
Can we close this issue now?

**Comment by ivanbusthomi** [comment] 2017-02-28 08:04
@timlinux yes, I agree. Thanks for the fix mas @lucernae

**Closed** 2017-02-28 08:05 UTC
Labels: Bug, Candidate for closing, In progress, Release Blocker
