### ISSUE TITLE
[Bug] IFCW: Cannot click next button after choose hazard data

### ISSUE THREAD

**Issue by adissadis** [inasafe/inasafe#2906] opened 2016-06-06 03:28 UTC
### Problem
I cannot click Next button when i want to select hazard from disk. The next button is unavailable even i already select the earthquake hazard.
![image](https://cloud.githubusercontent.com/assets/2520159/15811189/41b80d38-2bd0-11e6-8571-5e08e9b1a67e.png)

This problem also appear in IFCW using Tsunami and Flood. 

### Expected Behaviour
After i select EQ hazard from disk, i can click Next button to proceed to the next step.

### Environment
* InaSAFE : 3.4 from repository QGIS
* QGIS : 3.14.3
* OS : Windows 7 64 bit
* Data used :
  * Exposure : Java population or Sumatera population
  * Hazard : EQ Jogjakarta or Padang EQ, Maumere Tsunami, Flood HKV
  * Aggregation :

### Proposed Solution

cc:
@Charlotte-Morgan @ismailsunni @samnawi

**Comment by Charlotte-Morgan** [comment] 2016-06-06 04:57
Hi @borysiasty - I've put your name on this one.
It sounds like something we had once before?
@timlinux @Gustry

**Comment by borysiasty** [comment] 2016-06-06 20:59
It seems the browser lives its own life. LayerBrowserProxyModel is not set (the non-layer files like *.xml and *.qgs should be filtered out), and the selection signal is not connected (besides the unlocked button, there should be a layer keywords summary on the right). I'll be investigating it tomorrow.

**Comment by borysiasty** [comment] 2016-06-08 10:01
@ismailsunni: please see PR #2924

**Comment by NyakudyaA** [comment] 2016-06-09 14:11
@ismailsunni  has this been merged into develop yet. I am running develop and I still cannot click next.
![save](https://cloud.githubusercontent.com/assets/2510900/15932582/8e89e3aa-2e5c-11e6-9f23-78b8ab3aef54.png)

**Comment by borysiasty** [comment] 2016-06-09 14:55
@NyakudyaA: Please read the description on the right. The layer's classes are not suitable for the selected impact function (the incompatible parameter is always written with italic font).

**Comment by Gustry** [comment] 2016-06-09 14:59
Ok, so it might be related to https://github.com/inasafe/inasafe/issues/2941

I wonder why the colour is grey @borysiasty. And we should highlight what is wrong with the layer. In this case, it's `classes`.

**Comment by borysiasty** [comment] 2016-06-09 18:44
@Gustry The colour is grey in order to be consistent with the inactive `Next` button. It is gray if you select a layer that you can't use, and black if you can use it. I thought it's quite intuitive, but I'm not any UX guy... :) The italic font shows what is wrong. We could make it italic + bold, but to would be probably too much. Please note we are limited to the Qt palette.

**Comment by Charlotte-Morgan** [comment] 2016-06-10 04:44
Hi @Gustry and @borysiasty 
I can confirm that this is still a problem.
QGIS 2.14.3
InaSAFE 3.5 dev (assuming this has been merged)

## problem 1
I have a dataset with no key words assigned.
I am using the IFCW and chose eq on pop; raster on raster; ITB 
When i find my EQ raster on disk I am unable to select next

![image](https://cloud.githubusercontent.com/assets/5743135/15954337/e549c3d8-2eff-11e6-93d2-b2e1f9c6e80e.png)

## expected behaviour
I can select next and will immediately be taken to kw wizard to assign kw

## problem 2
I have a dataset with key words assigned.
I am using the IFCW and chose eq on pop; raster on raster; ITB function
When i find my EQ raster on disk I am unable to select next and it does not appear to have read the key words - ie there is no info on the right to show kw are being read

![image](https://cloud.githubusercontent.com/assets/5743135/15954370/6ce1cd4a-2f00-11e6-9d37-66a0703813d1.png)

## expected behaviour
I would expect to see the kw details in the right of the IFCW screen
I would expect to be able to click next because there are not really many options for EQ hazard kw

**Comment by Charlotte-Morgan** [comment] 2016-06-10 04:49
@NyakudyaA  - here is an example of it working
I select volcano polygon on raster population; polygon volcano on pop IF
when I select my data on disk, it tells me what KW it sees and what it is looking for (great +!)
![image](https://cloud.githubusercontent.com/assets/5743135/15954432/344ae538-2f01-11e6-8f8b-5630e4192fba.png)

I can backtrack through the wizard and choose volcano point on raster pop and the point volcano on pop IF
yay - my next button is active 

![image](https://cloud.githubusercontent.com/assets/5743135/15954445/6429d250-2f01-11e6-8b03-0ee2df47fe8f.png)

**Comment by Charlotte-Morgan** [comment] 2016-06-10 04:51
@Gustry - sometimes a user will select the wrong option for their available data and have to go back and change options to access the data they have.

What we do not accomodate is a dataset that has the wrong kw assigned :)

**Comment by NyakudyaA** [comment] 2016-06-10 12:27
@Gustry  I think it would be better to allow a user to redefine his keywords  in situations where his keywords are wrong. Rather than close IFCW and redefine KW and then come back again to IFCW.  
![redifine](https://cloud.githubusercontent.com/assets/2510900/15963963/24b0b016-2f16-11e6-8a48-e9b05955093b.png)
For the example above the  classes that are in the layer are  `flood_vector_hazard_classes` but the required classes are `generic_vector_hazard_classes`. So I suggest to ask the user whether he wants to redefine the keywords just to make it more interactive.

**Comment by Charlotte-Morgan** [comment] 2016-06-10 12:41
We need to consider two scenarios. 
Firstly, the user has selected the wrong IF for their data and needs to go back and choose the right if. This resembles the original plan for a data centric wizard. 
Secondly, the data have the wrong key words. This happens to me because i dodgy the data to try things. But should we expect this for normal users. 
I think we should assume the first scenario in most cases.

**Comment by borysiasty** [comment] 2016-06-10 13:17
@Charlotte-Morgan - just one note: your screenshots are from before my fix! Please ensure you reinstalled Inasafe (and reloaded QGIS) correctly. 

If you can see various unwanted files in the browser like .qgs and .xml, and only vector layers work (what is your case), it means your installation clearly doesn't contain the fix.

**Comment by Charlotte-Morgan** [comment] 2016-06-10 23:28
My apologies. 
I thought I had the latest version. 
As the ticket was closed I assumed the work was merged.

**Comment by borysiasty** [comment] 2016-06-11 12:12
The work is merged to develop. So as long as you see e.g. *.xml files in the browser, it seems you don't use the current develop :) Something didn't refresh. I don't know how do you install it - just by git pull from develop?

**Comment by timlinux** [comment] 2016-06-24 12:27
@NyakudyaA can you verify this is working now and get one of us to close it if it is working.

**Comment by NyakudyaA** [comment] 2016-06-24 12:49
@timlinux I cannot replicate this. The issue seems to be centered on defining key words. If the layer has wrong keywords then you cannot click next.

**Closed by NyakudyaA** 2016-06-24 12:49 UTC
Labels: Bug
