### ISSUE TITLE
Failing keywords migration

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#2762] opened 2016-05-04 12:24 UTC
### Problem
The attached file's keywords do not migrate cleanly when opening in 3.3

### Expected Behaviour

The layer should be correctly recognised and have proper keywords.

### Proposed Solution

Ismail please check the migration logic is working right for this.
[open_dri_admin_keyword_migration_fail.zip](https://github.com/inasafe/inasafe/files/248700/open_dri_admin_keyword_migration_fail.zip)

**Comment by timlinux** [comment] 2016-05-04 12:24
See also #2759

**Comment by ismailsunni** [comment] 2016-05-24 09:00
Hi @timlinux
I have investigated the issue, and I found the problem is data specific. Here is the keywords from the layer:
```
category: postprocessing
aggregation attribute: name
title: opendri_admin
elderly ratio attribute: Global default
youth ratio default: 0.26
elderly ratio default: 0.08
adult ratio attribute: Global default
female ratio attribute: Global default
youth ratio attribute: Global default
female ratio default: 0.5
adult ratio default: 0.66
```

AFAIK, this keyword is coming from long time ago. There is even no `layer_purpose` keyword, which makes inasafe throw an error. InaSAFE assumes there is `layer_purpose` key in the keyword to show the impact report or generic keyword.

I have a PR #2827 to check the mandatory keywords. Please check the PR, it will be no difference from user's POV, since you have added the proper error message.

**Comment by ismailsunni** [comment] 2016-05-25 01:32
Closing this on PR #2827

**Closed by ismailsunni** 2016-05-25 01:32 UTC
Labels: In progress
