### ISSUE TITLE
Displacement thresholds need to be shown in the impact function notes

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#3715] opened 2017-01-27 07:01 UTC
### Problem

When we run an analysis, we should show what the displacement rates used were.

### Proposed Solution

Please include a line in the notes to indicate what the rates used were e.g.

For this analysis, the following displacement rates were used: High - 50%, Medium: 10%, Low: 1%

**Comment by timlinux** [comment] 2017-01-27 09:32
See #3553

**Comment by lucernae** [comment] 2017-02-17 06:05
duplicate of #3877

**Closed** 2017-02-17 06:06 UTC
