### ISSUE TITLE
Zero affected when running Volcano Polygon on Buildings

### ISSUE THREAD

**Issue by ivanbusthomi** [inasafe/inasafe#3785] opened 2017-02-07 09:21 UTC
### Problem
When I tried running volcano polygon on buildings, I got zero total affected and Unaffected, even though there are buildings inside the hazard area. Instead, all of the buildings are marked as not exposed.
![image](https://cloud.githubusercontent.com/assets/7351977/22684885/cfd04b66-ed50-11e6-8327-47323417c934.png)

### Expected Behaviour
The result should properly shows the number of buildings affected and not affected

### Environment
* InaSAFE : 4.0 develop
* QGIS : 2.14.10
* OS : Windows
* Data used :Nageko dataset
  * Exposure : buildings (NGK_Buildings_WGS84.shp)
  * Hazard : Volcano Polygon (NGK_KRB_Ebulobo_WGS84.shp)
  * Aggregation : Villages (NGK_Villages_BPS_WGS84.shp)

### Proposed Solution
Make it happy

___
CC: @Gustry @timlinux @Charlotte-Morgan @samnawi @felix-yew @fredychandra

**Comment by Gustry** [comment] 2017-02-07 10:27
I tried, I couldn't replicate your issue : 
![screen shot 2017-02-07 at 11 26 18](https://cloud.githubusercontent.com/assets/1609292/22687436/51da6cbe-ed28-11e6-932d-68c3a4b3d3c0.png)

Did you launch the hazard keyword wizard ? I guess yes.
Can you tell me which extent or aggregation area it happens ?

**Comment by ivanbusthomi** [comment] 2017-02-08 02:04
Hi @gustry, I used the whole area with aggregation and without aggregation. Let me try it again.

**Comment by ivanbusthomi** [comment] 2017-02-08 02:19
Hmmm, I still got the bugs. @felix-yew or @samnawi could you also please check this?

**Comment by felix-yew** [comment] 2017-02-08 02:52
Hi, @ivanbusthomi I also get the same problem when running the buildings + volcano polygon, with the same data.
![image](https://cloud.githubusercontent.com/assets/13621886/22721477/929e95d4-ede3-11e6-95bd-e5e5f3dfdc78.png)
The result just show the not exposed (grey color) although the buildings inside the hazard area.

**Comment by samnawi** [comment] 2017-02-08 04:25
I guess.... the problem is come from the hazard data, because it's occurred on all of the exposure data.
**building**
![image](https://cloud.githubusercontent.com/assets/8871958/22722769/dbce5e08-edeb-11e6-93b2-bf077101eebb.png)
**building point**
![image](https://cloud.githubusercontent.com/assets/8871958/22722812/100512d4-edec-11e6-9dbd-54d6befabd07.png)
**landcover**
![image](https://cloud.githubusercontent.com/assets/8871958/22722792/f6250676-edeb-11e6-8624-cea8834fe074.png)
**population**
![image](https://cloud.githubusercontent.com/assets/8871958/22722826/22357624-edec-11e6-95ca-2a326a5232ff.png)
**roads**
![image](https://cloud.githubusercontent.com/assets/8871958/22722843/34cf8cc0-edec-11e6-8ed5-b3c0c43964c7.png)


When I try with Merapi dataset, the result is fine.
**building**
![image](https://cloud.githubusercontent.com/assets/8871958/22723112/567706ee-edee-11e6-9695-26d74064d100.png)
**roads**
![image](https://cloud.githubusercontent.com/assets/8871958/22723117/6ca0534e-edee-11e6-81e0-40ab7d50fa69.png)
**population**
![image](https://cloud.githubusercontent.com/assets/8871958/22723129/78a1f5d0-edee-11e6-90fc-c4a69aeeb61d.png)


When I try to check with some exposure in Sinabung, it's fine for building
![image](https://cloud.githubusercontent.com/assets/8871958/22723449/0d17e9f2-edf1-11e6-90cc-9e8a6bf3be55.png)
But, It's show zero result for roads
![image](https://cloud.githubusercontent.com/assets/8871958/22723478/506cbc46-edf1-11e6-966a-e72788d45137.png)

**Comment by felix-yew** [comment] 2017-02-10 08:32
I also find this case in drought potential zone (vector) vs population vector no aggregation.
![image](https://cloud.githubusercontent.com/assets/13621886/22819714/f172619e-efa5-11e6-99af-89387b8dac76.png)

**Comment by Gustry** [comment] 2017-02-10 08:42
Thanks a lot for your comments.
I will have a look.
@felix-yew Can you share your data for the last one ?

**Comment by lucernae** [comment] 2017-02-10 09:18
I think I need to see this too.

**Comment by Gustry** [comment] 2017-02-10 09:22
@lucernae The legend is also empty on the left side, so it's also in the summary calculation.

**Comment by Gustry** [comment] 2017-02-10 10:09
Looking at the data @ivanbusthomi the problem is in your keywords : 

The attribute table is not following your keywords : 
![screen shot 2017-02-10 at 11 01 18](https://cloud.githubusercontent.com/assets/1609292/22822781/1617bfdc-ef81-11e6-9920-50a62bed289b.png)

Run the keyword wizard and do a correct value mapping for the building exposure : 
![screen shot 2017-02-10 at 11 06 38](https://cloud.githubusercontent.com/assets/1609292/22822813/304740bc-ef81-11e6-8026-8bdfeb87d192.png)

And it works as expected : 
![screen shot 2017-02-10 at 11 06 17](https://cloud.githubusercontent.com/assets/1609292/22822823/3be05b7a-ef81-11e6-84b0-ecf34db1d49c.png)

Can we close this ticket ?

**Comment by ismailsunni** [comment] 2017-02-10 10:26
@ivanbusthomi @felix-yew @samnawi 
Yes, I discussed with @Gustry yesterday, and make an update to keyword wizard this morning. Like @Gustry said, it caused by "bad" value mapping. In my new update, you will see classify panel if you change the classification combo box. This will prevent the user from "bad" value mapping.

Can you try it again with the newer keyword wizard?

**Comment by ivanbusthomi** [comment] 2017-02-13 01:45
@ismailsunni OK I will try it again

**Comment by ismailsunni** [comment] 2017-02-13 03:05
@ivanbusthomi can we close this then?

**Closed** 2017-02-13 05:59 UTC
Labels: Awaiting feedback, Bug, Candidate for closing
