### ISSUE TITLE
InaSAFE analysis results are incorrect

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#3971] opened 2017-03-01 03:59 UTC
### problem ###
In a review of the analysis behavour for population exposure @samnawi has identified some incorrect analysis results.

The testing reviewed the analysis of population counts in exposure data and the application of ratios in aggregation data using both vector and raster population data.

Example 1.
In vector flood and raster population with vector aggregation - the global default age and gender ratios are applied regardless of whether the Do not use; Global default or Custom ratios are set in the aggregation key words.

Example 2.
In vector flood and vector population with vector aggregation; the results are inconsistent. The results are correct when no field is selected in exposure data and global defaults are used in aggregation layer.
The results are incorrect (approximately 10% of expected value) when fields are selected in the exposure data.
The results are incorrect when no field is selected in the exposure data and a ratio is selected from the aggregation layer

### proposed solution ###
example 1.
the radio buttons in the aggregation data should be applied in preference to global defaults if set.

example 2.
the results produced by different analysis methods should produce similar results.
The results should be 'correct' ish.

... more to follow ... the situation with vector population data is more complicated

**Comment by samnawi** [comment] 2017-03-01 08:33
I try to investigate the behavior of InaSAFE population analysis to calculate age & gender.
I the table below, show the result of the analysis that I doing today.

Hazard : Jakarta Flood (Peta Bencana.id)
Population : Dummy Vector Population
Aggregation : Dummy Aggregation

![image](https://cloud.githubusercontent.com/assets/8871958/23451209/8939923c-fe91-11e6-9950-c69054e7b56f.png)

Hazard : Jakarta Flood (Peta Bencana.id)
Population : Raster Population (InaRISK Data)
Aggregation : Dummy Aggregation

![image](https://cloud.githubusercontent.com/assets/8871958/23451229/99f7936c-fe91-11e6-887c-1520ce97ccc1.png)

According to the result in above, I try to create a conclusion of the InaSAFE Behaviour to calculate age and gender ratio (**Just focus on the red color**)
![image](https://cloud.githubusercontent.com/assets/8871958/23451285/d9abb9fc-fe91-11e6-876c-df5d1fdaa802.png)


And this is the attribute table of the population and aggregation
**Population**
![image](https://cloud.githubusercontent.com/assets/8871958/23451040/b876d52e-fe90-11e6-93fe-8b177bef2bd5.png)

**Aggregation**
![image](https://cloud.githubusercontent.com/assets/8871958/23451339/19bd61e4-fe92-11e6-8d5c-7f04971a2555.png)

> The results are incorrect when no field is selected in the exposure data and a ratio is selected from the aggregation layer

I'm sorry @Charlotte-Morgan apparently this problem is my mistake to write the ratio, because based on the aggregation table in above compare with the result table, there is no problem in here. 

You can download the data in [here ](https://drive.google.com/open?id=0B3b8OAVI_hAiZ3g1YmM3NXZLZWc) (Sorry, I have a problem to upload zip file in here)

Thank you.

**Comment by samnawi** [comment] 2017-03-01 09:08
Hi all, 

This is the debug file for 3 problems that I highlight in above.
The folder name refers to the ID process in above.
Please find the data in [here](https://drive.google.com/open?id=0B3b8OAVI_hAiZjNoSjNWeW5EUkE).

Thank you.

**Comment by ismailsunni** [comment] 2017-03-02 09:05
After some discussion with @Gustry the first case (vector count) is related to #3973. The problem is we use wrong formula for ratio. I will fix it soon.

**Comment by Gustry** [comment] 2017-03-02 15:13
@ismailsunni is fixing this issue with vector exposure at the same time as #3973
I'm fixing this issue with raster exposure in the PR above.

**Comment by samnawi** [comment] 2017-03-03 03:51
Yeah @Gustry I think this issue was fixed in https://github.com/inasafe/inasafe/pull/3984

**Comment by Charlotte-Morgan** [comment] 2017-03-09 06:11
can we confirm this is fixed and close the ticket please

**Comment by Gustry** [comment] 2017-03-27 20:20
This ticket should be fixed. Feel free to open a ticket if you have a similar problem.

**Closed by Gustry** 2017-03-27 20:20 UTC
Labels: Candidate for closing, Release Blocker
