### ISSUE TITLE
[BUG] VerificationError when running vector Flood IF with raster population

### ISSUE THREAD

**Issue by dewisulistio** [inasafe/inasafe#2560] opened 2016-01-12 02:54 UTC
# Problem 
VerificationError when running vector Flood IF with raster population using Aggregate DKI Jakarta District

# Detail  
I try to run flood IF using flood Jakarta (vector) and Java Population (raster) with Aggregate Jakarta Dsitrict. The result not appear because problem VerificationError. But when I try to run with entire area it's working.

# Screenshot  
![flood bug](https://cloud.githubusercontent.com/assets/2524177/12253048/625c29cc-b90f-11e5-89c6-fbbdb988dfa1.png)

# Platfrom
Windows 7 64 Bit
RAM 4 GB
QGIS 2.8.4 Wien
InaSAFE 3.3.0 dev-master

# Data
Hazard : Jakarta_Flood_18113__WGS84.shp (Vector)

Exposure : 
Java_Population_WGS84.tiff (Raster)

Agregation : Jakarta_District_Boundary.shp

cc : @timlinux @ismailsunni

**Comment by ismailsunni** [comment] 2016-01-12 03:37
Hi @dewisulistio 

Can you paste the full report here? And where can I get the data?

**Comment by dewisulistio** [comment] 2016-01-12 03:55
Hi @ismailsunni 
Details from InaSAFE dock
These additional details were reported when the problem occurred.

* An exception occurred when running the impact analysis.
* Layer did not have required keyword "layer_purpose". Please add keywords as : pairs in the .xml file. For more information please read the sections on impact functions and keywords in the InaSAFE website: http://inasafe.org/en/developer-docs/

You can get data from Flood Jakarta 2013 (https://data.inasafe.org/InaSAFE%203.2%20Data/)

**Comment by ismailsunni** [comment] 2016-01-12 04:05
Hi @dewisulistio, based on the error message, it seems you need to assign the keywords. Can you try assign it? It seems the aggregation layer doesn't have proper keywords.

And when I can get the Java pop data?

**Comment by dewisulistio** [comment] 2016-01-12 04:16
I have set the keywords for aggregate Jakarta District and it's working with raster flood (HKV) and Java pop data. You can get the Java pop data in https://data.inasafe.org/InaSAFE%203.2%20Data/ > DKI Jakarta > Exposure Data

**Comment by ismailsunni** [comment] 2016-01-12 04:30
Ok, so the problem is we need to set the aggregation layer's keyword properly first. We need to add this checking later. Actually, the error message is quite helping. But, we need add better handling for the error.

I will close this comment then. Please reopen if still failed.

PS : Actually, after I tried the scenario, all is good.

**Closed by ismailsunni** 2016-01-12 04:30 UTC
