### ISSUE TITLE
Realtime Volcanic Ash Testing

### ISSUE THREAD

**Issue by ivanbusthomi** [inasafe/inasafe#3285] opened 2016-10-11 04:04 UTC
The old ticket in #2491 has become too long to track. Now that we are in the testing stage, I propose we move the discussion regarding the testing to this new ticket. I will keep the old ticket open as future reference.

[Old ticket link](https://github.com/inasafe/inasafe/issues/2491)
Some notable reference:
- link to staging server (**online**): http://staging.realtime.inasafe.org/realtime/
- link to temporary staging server: http://196.214.55.116:61100/realtime/
- login steps : https://github.com/inasafe/inasafe/issues/2491#issuecomment-252524564
- current landing page at temporary staging server
  ![interface](https://cloud.githubusercontent.com/assets/7351977/19258445/1a42be66-8fa2-11e6-8172-aaec3aae6a6f.PNG)
- current report template (generated from the temporary staging server)
  ![template](https://cloud.githubusercontent.com/assets/7351977/19258450/1fd0314c-8fa2-11e6-95af-77a166bfce5f.PNG)

@lucernae feel free to give status update in here. :smile: 

---

**CC** @Charlotte-Morgan @timlinux @lucernae @samnawi @adelebearcrozier @felix-yew @fredychandra

**Comment by adelebearcrozier** [comment] 2016-10-12 00:04
hi @ivanbusthomi and @lucernae - I generated a tif for soputan in WGS 84 (EPSG:4326). I created an event but still no report generated. I also noticed it put the event time as "in 11 hours" (future). Not sure why, i selected the current date and time. The tiff is named 'soputan.tiff'. Is it possible to check if the problem is again with my CRS?

**Comment by lucernae** [comment] 2016-10-12 10:38
I think the event time is a bug on my part. I'm still not sure on how to properly convert the timezone.
As for the tif file, I downloaded it and open it on QGIS, I saw the CRS is correctly displayed as WGS 84 (EPSG:4326), however the extent is wrong. The extent I got from the file is this:

```591242.4966442952863872,20642.4966442952863872 : 793893.5033557047136128,223293.5033557046845090```

I think it is way too big in that CRS, but CMIIW since I'm no GIS expert myself :D.
The extent I got from previous Soputan hazard which I converted using QGIS is this:

```123.8199494312289772,0.1865595521267480 : 125.6418342597790030,2.0199896275106921```

It might be because of the extent was not overlapping any part of the population data, so the report failed to be generated. If I may ask, how did you convert the tif?

**Comment by lucernae** [comment] 2016-10-12 10:45
Oh, by the way if you wanted to inspect each entry in detail, you could go to the admin page (click the button called "Admin Page" under the welcome menu saying "Hi, Volcano Test" on the top right corner), from there you can navigate to Ashs model (now that I wrote it, I think it should be Ashes, sorry), then you can see which Ash entry you want to see or download the tif file used for that entry.

**Comment by ivanbusthomi** [comment] 2016-10-17 02:06
Hi @adelebearcrozier,

Sorry for the late reply. 
I guess when you generated the CDF file, it assigned a coordinate system to the file, either it is in Geographic (WGS84) or in Projected (ie UTM).
Then, when you convert the CDF into tiff using the NetCDF converter, the coordinate selector in the converter only assign the coordinate reference system of the file, not transforming it. It is because information about the coordinate system created when the CDF was created is not saved in the metadata, thus I cannot automatically transform it into Geographic coordinate system.

**My suggestion is:**
when you convert the CDF using the tool, you should select the correct coordinate system based on CDF file, not the system you want to convert too. Then you can manually transform the coordinate system inside QGIS. I will upload the gif containing the steps to transform the CRS of the layer soon.

**My Question**
Is there any information about coordinate system in the CDF metadata that I can access? because if I want to automatically transform the input file, I need to know what  coordinate system. And I can't find that information in the metadata.

**Comment by adelebearcrozier** [comment] 2016-10-17 05:33
Hi @ivanbusthomi,

No worries, apologies for the problems i am causing. I don't seem to be
having any luck converting the netcdf to the correct format (as you say
above). I'm sure its not that difficult but i am missing something
somewhere. Would it be possible to send you the Soputan netCDF i am trying
to convert? - that way you can check if it is a problem with my data and
perhaps show me step by step how to convert and generate a report? Ivge
included a google link to the file with this email. Let me know if you have
any issues accessing it. ​
 soputan_forecast_2016.res.nc
<https://drive.google.com/file/d/0B9XeBru2QyndVFRnNDZ5d0hKcm8/view?usp=drive_web>
​

In answer to your question, no the CRS is not captured in our netCDF or
metdata. Our netCDF contains the bounding coordinates of the model domain
("lat/lon" if geographic or "x/y" if UTM) but no further information than
that.

Many thanks for your patience - Cheers Adele

**Comment by ivanbusthomi** [comment] 2016-10-22 02:47
Hi everyone, please welcome @estukriswati and @prastanti to the discussion

**Comment by willi09** [comment] 2016-10-22 07:50
please edit some point information in the realtime report etc:
a. the location information of the volcano..please deleted the word Longitude and Latitude,,because there are clear if there are S (for South) and E (for east)
b. the second is about the eruption column height, in your report : Eruption Column Height (a.s.l) -2968
the right one is : Eruption Column Height : 5000 m asl (notice is eruption column height is the volcano height plus with the ash height).

**Comment by Charlotte-Morgan** [comment] 2016-10-22 07:51
welcome @willi09 - thanks for your feedback

**Comment by willi09** [comment] 2016-10-22 08:27
please edit some point information in the realtime report etc:
a. the location information of the volcano..please deleted the word Longitude and Latitude,,because there are clear if there are S (for South) and E (for east)
b. the second is about the eruption column height, in your report : Eruption Column Height (a.s.l) -2968
the right one is, example : Eruption Column Height : 5000 m asl (eruption column height is the volcano height plus with the ash height). (based on VONA data report)
@Charlotte-Morgan please if you can resolve this

**Comment by ivanbusthomi** [comment] 2016-10-22 08:29
Hi @adelebearcrozier,
Mas Rizky @lucernae already fix the problem of the report not being generated. If you try uploading the ash again, I think it is working right now. 
**CC** @estukriswati, @willi09 and @prastanti

**Comment by Charlotte-Morgan** [comment] 2016-10-22 08:32
@willi09  - i think this is easy.
@ivanbusthomi  - please update the template to remove the words in point a above
@lucernae - please add an element in the data upload form to include the ash height

Column height on the impact report needs to be ash height + volcano height - maybe this needs a ne token
Thanks

**Comment by Charlotte-Morgan** [comment] 2016-10-22 08:35
@ivanbusthomi 
Other feedback on the report header from @timlinux 
Please make the words Volcanic Ash Impact  to one line
Please put the alert level on one line

And for the disclaimer - I think we need more space so the text is not truncated

**Comment by Charlotte-Morgan** [comment] 2016-10-22 09:36
During the code sprint with Kartoza, DMI and PVMBG there has been a lot of discussion regarding the volcanic ash realtime product and details in the impact report. One substantial area of discussion with how ash real time analysis can be used to support the warning and evacuation reports prepared by PVMBG for  BNPB. 
The proposed additional evacuation report would require new analyses to determine the number of people to evacuate in very high ash fall forecast areas. In the first instance, it requires the combination of realtime ash forecast data with historical  KRB flow data to then look at the number of people in specific areas.
It may also involve the use of 2 realtime models, 1 for ash and 1 for pyroclastic flows to be combined and the impact on people estimated.
This is an excellent use case and demonstrates end to end  link from credible hazard science through technology tools to support informed DM decisions. 

The sprinters agree that this is a great use case but represents a significant change in scope for the  realtime ash RFC as per #2491 

The sprinters agree to test, release and use the current version of ash realtime  and to work together to document requirements for an evacuation report if there is a subsequent version of realtime. This will need to be discussed between PVMBG, GA, DMI, and listed in agreed work plans :) with a new RFC to be developed.

Lets make it happen :)

@adelebearcrozier @estukriswati @heriwaseso @willi09 @RikkiWeber @ivanbusthomi @timlinux @lucernae

**Comment by ivanbusthomi** [comment] 2016-10-25 08:49
hi @lucernae , in addition to Pak @willi09 comment above, here are a few feedbacks from last week code sprint meeting.
- [ ] Change the UI colour when selecting mountain in uploading the ash.

![uploadash](https://cloud.githubusercontent.com/assets/7351977/19678627/b5a6981a-9ac8-11e6-912f-048af12d8548.PNG)

- [ ] Support input file in other Coordinate system, not only in WGS84 (I am not sure whether this one is going to be too much work for current version)
- [ ] Standard time and date format, not dynamically changing like the current one.
- [ ] drop-down list for alert level, to prevent unnecessary varying value.
![list](https://cloud.githubusercontent.com/assets/7351977/19678777/65bdbd46-9ac9-11e6-8d6e-58aa2ff9d083.PNG)

Ibu @estukriswati, Pak @heriwaseso , Pak @willi09 and Ibu @prastanti, feel free to remind me if I miss some points. Mas @lucernae, I hope these changes are not too difficult to be implemented.

___
**CC** @Charlotte-Morgan @timlinux @adelebearcrozier

**Comment by Charlotte-Morgan** [comment] 2016-10-25 18:37
Sure. I can help

Charlotte  Morgan
Spatial Data Analyst
DMInnovation - Jakarta
GEOSCIENCE AUSTRALIA

Mobile: +61 412 949642
Mobile: +62 8118204648


On 22 Oct 2016, at 2:46 PM, willi09 <notifications@github.com<mailto:notifications@github.com>> wrote:


please edit some point information in the realtime report etc:
a. the location information of the volcano..please deleted the word Longitude and Latitude,,because there are clear if there are S (for South) and E (for east)
b. the second is about the eruption column height, in your report : Eruption Column Height (a.s.l) -2968
the right one is : Eruption Column Height : 5000 m asl (notice is eruption column height is the volcano height plus with the ash height).

-

**Comment by Charlotte-Morgan** [comment] 2016-11-28 04:36
Hi @lucernae - I just realised that this follow up work from the code sprint had not been assigned to you :( 
Is it possible for you to review the edit requests and implement them soon. We would really like to wrap this work up by the end of the month to meet reporting requirements.
cc @timlinux

**Comment by ivanbusthomi** [comment] 2016-12-01 03:43
Hi @Charlotte-Morgan and @timlinux 
I've already informed Ibu @estukriswati about the current state of the realtime volcanic ash website and also the report, and still waiting the feedback from her.

mas @lucernae , when I tried opening the report from the page, I keep receiving pop-up messages that the report is still being generated. When I tried checking the directory in *Home > Realtime Application > Ash Reports* , the reports for the ash event are actually there and have been generated. Could you please investigate it? thanks

**Comment by ivanbusthomi** [comment] 2016-12-02 03:51
## Status Update
Selamat Siang Ibu @estukriswati, Mas @willi09 and Mba @prastanti,
This is summary of some tweaks that has been added by Mas Rizky Maulana (@lucernae ) to the staging version of Realtime Volcanic Ash website based on our discussion in the Codesprint Meeting .
### Report Template
* Latitude and Longitude words on location section in the report has been removed.
![image](https://cloud.githubusercontent.com/assets/7351977/20822112/8831fca6-b87a-11e6-8398-594bad414689.png)
* Updating the title to be one lined
![image](https://cloud.githubusercontent.com/assets/7351977/20822302/2aa64b9e-b87c-11e6-81a1-9c61755a32bc.png)

### Volcanic Ash Realtime webpage
* the color for volcano selection in the upload ash page has been adjusted to make it easier to see.
![image](https://cloud.githubusercontent.com/assets/7351977/20822287/f926bc7a-b87b-11e6-80d7-8357adee22f7.png)
* an additional input for eruption column height has been added in the upload ash page.
![image](https://cloud.githubusercontent.com/assets/7351977/20822281/e85a17a2-b87b-11e6-919a-6b3b6ec44b3b.png)
* Input type for alert level in the upload ash page has been changed to drop-down type to make the user input uniform.
![image](https://cloud.githubusercontent.com/assets/7351977/20822262/c62f3ca2-b87b-11e6-99e1-c1b113b2b315.png)
* Standard date and time format has been applied in the ash event list for easier reference.
![image](https://cloud.githubusercontent.com/assets/7351977/20822211/5f147474-b87b-11e6-9477-ff0266fd9e8d.png)

Feel free to test it in the staging.realtime.inasafe.org. I am looking forward to hear what you think about the update, and if you already satisfied with it maybe we can proceed to release current version of the volcanic ash realtime.
___
**CC** @Charlotte-Morgan @timlinux @samnawi @adelebearcrozier @heriwaseso

**Comment by Charlotte-Morgan** [comment] 2016-12-02 04:07
Wow - thanks @lucernae for fixing all these things and @ivanbusthomi for the update :)

**Comment by timlinux** [comment] 2016-12-02 07:30
@lucernae yes thank you from me too - I know you had a lot going on this week so well done for your effort, and thanks to @ivanbusthomi for helping us to keep our eye on the ball

**Comment by lucernae** [comment] 2016-12-02 09:48
I added a timezone field (Read only).
Just to make the user remember that the time he input is based on the timezone he currently in.
This is to fix some discrepancies with the timezone. 
The time in the report itself will be displayed in WIB (GMT+07:00).
So, for example, if a mountain erupts at 15:00:00 in WIB, then if the user is filling the form from Makassar (GMT+08:00), then he should fill 16:00:00.
The report will display 15:00:00 (GMT+07:00).
You can provide feedback on this one.

<img width="795" alt="screen shot 2016-12-02 at 10 41 44" src="https://cloud.githubusercontent.com/assets/831865/20829441/5c70912a-b87c-11e6-9f27-38e4955e3d0c.png">

**Comment by Charlotte-Morgan** [comment] 2016-12-02 10:07
Hi Rizky
Can you also look at the landing page and make the default order to have most recent reports on the top?
Thanks

**Comment by Charlotte-Morgan** [comment] 2016-12-07 08:29
Hi @lucernae, I notice on the upload ash button the use is asked to upload a collection of hazard files in zip format.  For volcanic ash realtime, we expect the user to upload a single tiff file. This is created using the ash modelling software and then the netcdf to tiff converter.  There will be only one file for each ash event entered by a user.  Could you please change the upload parameters to expect a single *.tiff file?
@willi09  @estukriswati @prastanti - if there are other files you wish to share eg KRB shape files, we need to find a different way to share data outside of the ash data upload button.
 cc @adelebearcrozier @timlinux

**Comment by Charlotte-Morgan** [comment] 2016-12-19 06:24
Hi @lucernae  - please remove reference to zip file in the upload page. This is misleading for users. thank you

**Comment by lucernae** [comment] 2016-12-19 06:27
@Charlotte-Morgan I'm trying to fix it with some other bug in the report. Also, just for confirmations: do I need to accomodate shapefile too now?

**Comment by Charlotte-Morgan** [comment] 2016-12-19 06:29
@lucernae  - please see my comment above. The only input for now is *.tiff file.

**Comment by Charlotte-Morgan** [comment] 2017-01-12 02:31
@lucernae - we would really like to see these fixes implemented so that we can work with partners to deliver this product.

@timlinux

**Comment by lucernae** [comment] 2017-01-12 03:31
If it's a priority, I can work on this first.

**Comment by timlinux** [comment] 2017-01-30 18:53
Closing this as the realtime work has been moved to its own repo and a ticket has been opened there.

**Closed by timlinux** 2017-01-30 18:53 UTC
Labels: Ready, Realtime
