### ISSUE TITLE
Min Needs Calculator: incomplete report

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#3499] opened 2016-12-16 07:03 UTC
# problem 
The min needs calculator returns spatial data with values for min needs but has no reference to the input fields. eg attribute table of output data
![image](https://cloud.githubusercontent.com/assets/5743135/21254575/c5c20bfa-c398-11e6-865c-8364a783cddd.png)

see #3498 for sample input data

# proposed solution - part 1
Include the input fields in the output results
![image](https://cloud.githubusercontent.com/assets/5743135/21254609/fdc2d854-c398-11e6-814f-a4ddc9ff16d6.png)

# proposed solution - part 2
Ask the user for an id or name field to include in the output as well 

example table of results fo the sample data with subdistrict name, no of affected people and min needs

![image](https://cloud.githubusercontent.com/assets/5743135/21254657/5ed88076-c399-11e6-8b07-2eb163fa13be.png)

# relevance
Following the Aceh earthquake - BNPB requested support to calculate min needs for the actual displaced people. These data are used in this example

**Comment by timlinux** [comment] 2016-12-17 08:49
@ismailsunni can confirm but in 4.0 all these additional data should be written in the attribute table and not only in the JSON. So the question is do you need a quicker short term fix? We could as a quick fix write out the needs data to a caveat file...

**Comment by timlinux** [comment] 2016-12-17 08:49
Sorry I meant CSV file

**Comment by Charlotte-Morgan** [comment] 2017-01-16 07:39
@timlinux - this is also for the min needs tool

**Comment by timlinux** [comment] 2017-01-16 17:13
@myarjunar Probably this is for you since you will be looking at this tool

**Comment by myarjunar** [comment] 2017-01-30 11:38
closed in #3645

**Closed by myarjunar** 2017-01-30 11:38 UTC
Labels: Paper cut
