### ISSUE TITLE
BUG: Wizard does not recognise tsunami hazard as continuous raster

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#2664] opened 2016-03-09 10:45 UTC
# problem
when using the IFCW to look at tsunami raster  on population raster  (ie standard Maumere data) the user is offered 3 IF options - classified raster, continuous raster and tsunami evacuation function.

When standard maumere continuous raster tsunami hazard and continuous raster population data are in QGIS with keywords; if the user selects the continuous raster IF option, the wizard says that no suitable data are available in QGIS.

Select IF
![image](https://cloud.githubusercontent.com/assets/5743135/13633095/aaa50734-e61f-11e5-810b-d492e4de1812.png)

Returns this
![image](https://cloud.githubusercontent.com/assets/5743135/13633121/be39e47c-e61f-11e5-84e6-15008cefefba.png)

Even though these data and keywords are in QGIS
![image](https://cloud.githubusercontent.com/assets/5743135/13633154/e49db6b6-e61f-11e5-9f1f-2bb701cb9481.png)

![image](https://cloud.githubusercontent.com/assets/5743135/13633170/f3e5eb02-e61f-11e5-9749-c9498fd17100.png)

# proposed solution
I would expect the wizard should recognise continuous raster data as suitable for both the continuous raster If and the tsunami evacuation function.

# cc
@easmetz @timlinux @borysiasty @ismailsunni

**Comment by timlinux** [comment] 2016-03-10 07:40
Ok I just tested and I can replicate here. Looking into why it is the case.

**Comment by timlinux** [comment] 2016-03-10 07:44
I also noticed that even though the IF is selected fine in the dock, the run button is disabled.

<img width="346" alt="screen shot 2016-03-10 at 09 42 41" src="https://cloud.githubusercontent.com/assets/178003/13662620/950d7084-e6a4-11e5-9cbe-1f96657a370d.png">

**Comment by NyakudyaA** [comment] 2016-08-04 13:48
@timlinux 
I have tested this and it seems the issue is not the wizard. Its a keywords issue. From the screen shots above it shows the units of measurement as meters whilst the tsunami IF expects it to be generic.

![maumere](https://cloud.githubusercontent.com/assets/2510900/17403564/adfe1544-5a58-11e6-8163-e632a6bed7c1.png)

With the layer having correct units of measurement you are able to select it.
![tsunami1](https://cloud.githubusercontent.com/assets/2510900/17403845/bd598f54-5a59-11e6-9de4-22908bcab495.png)

And then choose the layer.
![xzv](https://cloud.githubusercontent.com/assets/2510900/17404035/a541c21e-5a5a-11e6-9606-b7b4264d236e.png)

**Comment by ismailsunni** [comment] 2016-08-08 10:36
I think this is the expected behaviour of InaSAFE. You should assign `generic` unit if you want to use the `Continuous raster hazard on population` IF. The tsunami evacuation IF works with metres, and Continuous raster hazard on population is generic IF, that works with classes/zone.

I will close this. Feel free to reopen for more discussion.

**Closed by ismailsunni** 2016-08-08 10:36 UTC
Labels: Bug, In progress
