### ISSUE TITLE
BUG : Wrong Classification in the inundated building

### ISSUE THREAD

**Issue by samnawi** [inasafe/inasafe#2419] opened 2015-09-28 04:35 UTC
# Problem

When I run InaSAFE using flood raster VS building, I found some building that get wrong classification in the result. As in this picture :
![selection_219](https://cloud.githubusercontent.com/assets/8871958/10127591/5e1f5184-65ce-11e5-8770-0c2e49f3ea25.png)

Based on the legend, the dark blue has >= 1 m depth, the light blue has 0.5 - 1 m depth, and the cyan has 0.1 - 0.5 m depth.
Some of building that 100% located in depth < 1 m, is categorized to inundated (>= 1.0 m) - red color.
Some of building that 100% located in depth >= 1 m, is categorized to wet ( 0 m - 1.0 m) - orange color.

So, I think this issue will be influence the result, and the result possibly has incorrect value.
# PC Platform

Linux Ubuntu 14.04 and Windows 7 64-Bit
QGIS 2.8.3
InaSAFE 3.2 release version
# Proposed Solution

Make it Happy
# CC

@Charlotte-Morgan @fredychandra @timlinux 

Thank you.

**Comment by Charlotte-Morgan** [comment] 2015-09-29 09:43
I think the "make it happy", needs to look at the analysis extent. Looks like buildings are being included in the impact assessment when they are not coincident with the hazard data.
@ismailsunni - i've assigned this to you, but feel free to pass it on :)

**Comment by ismailsunni** [comment] 2015-10-01 16:02
It seems @timlinux will know better than me. So, I will pass it to him :). It can be related with analysis extent or interpolation

**Comment by timlinux** [comment] 2015-10-22 09:46
Probably something that will be fixed by switching to pixel lookups rather than interpolation...

**Comment by adissadis** [comment] 2015-12-22 04:02
I got this same issue like @samnawi . This issue not only affected to Building polygon but also building points. See my pictures below:
![image](https://cloud.githubusercontent.com/assets/2520159/11947535/d3969616-a89a-11e5-82c2-16b7eeee37a2.png)

It's look like the hazard raster data create some virtual buffer around the hazard area (probably around 8 meters) from pixel who categorize as affected area. This will cause building around those pixel will categorized as affected:
![image](https://cloud.githubusercontent.com/assets/2520159/11947557/4fcf4174-a89b-11e5-8eae-1812346fb551.png)

# Platform
Windows 7
QGIS 2.8.4
InaSAFE 3.2.5 dev-master (sync with Github at 21 December 2015)

**Comment by timlinux** [comment] 2016-01-22 11:14
@adissadis This is just classical interpolation effect. Consider this diagram taken from wikipedia:


![](https://upload.wikimedia.org/wikipedia/commons/c/c6/Bilininterp.png)
https://en.wikipedia.org/wiki/Linear_interpolation

You can see that the cells in the center of the diagram are influenced by the cells in the corners (which are the basis for interpolation. 

In 3.4 we will work to replace interpolation with pixel lookups which will give a much more 'humanistic' result, closer to what you are expecting to see. For now it is important to explain to users during training the fact that interpolation is used to derive flood depth and how the resulting dataset should be interpreted appropriately.

Because of this, I think we should close this issue since it is 'expected behaviour' and we will open  new ticket to replace all places that use interpolation with direct pixel lookups.

**Comment by timlinux** [comment] 2016-02-18 13:24
I have removed blocker for now - at teh moment we need to explain to people how to interpret the results, meanwhile in 3.4 we will work towards replacing such interpolation with direct value lookups which should resolve this issue.

**Comment by Charlotte-Morgan** [comment] 2016-05-25 09:53
hi @timlinux - has this progressed for 3.4?

**Comment by timlinux** [comment] 2016-06-22 08:10
@Charlotte-Morgan no - I think we must move this again to 3.6 where we can work on implementing our '7 base classes' and not do interpolation any more.

**Comment by Gustry** [comment] 2017-01-17 17:38
Interpolation has been removed in InaSAFE V4. We can now close this ticket.

**Closed by Gustry** 2017-01-17 17:38 UTC
Labels: Bug
