### ISSUE TITLE
expand keyword creation wizard columns to fit window

### ISSUE THREAD

**Issue by gubuntu** [inasafe/inasafe#3480] opened 2016-11-30 04:48 UTC
### Problem
in the two-column view used to assigned keywords to categories, if you expand the window, the columns widen but they remain the same height (sometimes they widen beyond the window, which might be related)

### Expected Behaviour
The column height should resize to fit the window, so the user can see the maximum number of categories

### Environment
* InaSAFE : 3.5.2
* QGIS : 2.14.7
* OS : Ubuntu 16.04
* Data used :
  * Exposure : osm buildings
  * Hazard : 
  * Aggregation :

**Comment by Gustry** [comment] 2016-12-08 11:43
I think it's a duplicate of https://github.com/inasafe/inasafe/issues/2975, I'm going to close this one.

**Closed by Gustry** 2016-12-08 11:43 UTC
