### ISSUE TITLE
[Bug] Aggregation Issue

### ISSUE THREAD

**Issue by samnawi** [inasafe/inasafe#2751] opened 2016-05-02 11:49 UTC
### Problem
I've got some error message when I run Population Analysis with aggregation.
![image](https://cloud.githubusercontent.com/assets/8871958/14953523/8d3ffd26-1094-11e6-8ead-464d99bc809f.png)

Data : 
[Nagekeo Sample Data](http://data.inasafe.org/InaSAFE%203.2%20Data/Nagekeo.zip)
Flood Data --> [NGK Flood](https://www.dropbox.com/s/xlkr09qmtwuto2j/NGK_Flood.zip?dl=0)

Error message :
**Develop 3.3.0**
![screenshot_20](https://cloud.githubusercontent.com/assets/8871958/14953649/bfaa6444-1095-11e6-9b79-3fa82059e79b.png)

**Master 3.3.2**
![screenshot_18](https://cloud.githubusercontent.com/assets/8871958/14953688/2a6d735c-1096-11e6-8a4b-6e9b6ce7765a.png)

### Environment
QGIS 2.8.8
InaSAFE 3.3.2 and 3.3.0-Dev

### Proposed Solution
Make it happy

Thank you.

## CC
@Charlotte-Morgan @timlinux @ismailsunni

**Comment by samnawi** [comment] 2016-05-03 02:20
**FYI**
For flood and generic hazard, the IF could run in InaSAFE 3.2.6. 
But, I still got the error message when run IF for volcano polygon.

**Comment by felix-yew** [comment] 2016-05-03 04:29
@samnawi maybe I can add a little information about it. I have tried Aggregation Issue in QGIS 2.14.1, too. And I have the same problems if I run the attached data from you. 

**QGIS 2.14.1 and InaSAFE 3.3.2 (master)**
Hazard data of **drought** (generic), **Ebulobo KRB** (volcano polygon), and **NGK flood**, **they can not be processed properly.** The problem is same, **VerificationError**. 
**Error in drought analysis**:
![ngk_drought_gen_sp2010_village_qgis2 14-ina3 3 2](https://cloud.githubusercontent.com/assets/13621886/14973890/4a9c63ae-1118-11e6-8300-e799611cf612.PNG)

**Error in flood analysis**:
![ngk_flood_sp2010_village_qgis2 14-ina3 3 2](https://cloud.githubusercontent.com/assets/13621886/14973906/7353c3f0-1118-11e6-9cc1-2073f8c9db05.PNG)

**Error in volcano (polygon) analysis**:
![ngk_volcano_poly_sp2010_village_qgis2 14-ina3 3 2](https://cloud.githubusercontent.com/assets/13621886/14973910/8ad68a9e-1118-11e6-9ef5-49c09e926e95.PNG)
**In this case, my QGIS is not responding**.

**with QGIS 2.14.1 and InaSAFE 3.3.0. (develop)**
The hazard data of **drought** (generic) and **Ebulobo KRB** (volcano polygon), they **can not be processed properly**. The problem is same, **AttributeError.**
**Error in volcano (polygon) analysis**:
![ngk_volcano_poly_sp2010_village_qgis2 14-ina3 3 0 dev-master](https://cloud.githubusercontent.com/assets/13621886/14974269/2080693a-111d-11e6-9e4b-a9cba0de7913.PNG)

**Error in drought analysis**:
![ngk_drought_gen_sp2010_village_qgis2 14-ina3 3 0 dev-master_notwork](https://cloud.githubusercontent.com/assets/13621886/14974270/2e5b650a-111d-11e6-8c3c-cba9c66fb10b.PNG)

So, If I run Population Analysis with aggregation in QGIS 2.14.1 and InaSAFE (master and/or develop), **the conclusion is**:
![image](https://cloud.githubusercontent.com/assets/13621886/14974416/c39192e2-111e-11e6-816f-7860e7466973.png)

**Comment by samnawi** [comment] 2016-05-11 03:29
Hi @ismailsunni Is there any progress on this issue, because in InaSAFE 3.3.2, I could run Generic hazard and Flood very well.

Or because you already finish to doing some effort in Aggregation issue, so I can do that?

**Comment by ismailsunni** [comment] 2016-05-11 06:21
hi @samnawi 
I just realised that this issue is the same as #2724 
You can test it again from develop since I have fixed it.

**Comment by samnawi** [comment] 2016-05-12 03:08
Yeah @ismailsunni I could run the analysis using Generic hazard and flood. But, I still got a problem when I run the volcano polygon IF, Either when I set the hazard in volcanic class or generic class.

```
Problem

The following problem(s) were encountered whilst running the analysis.

error
Suggestion

You can try the following to resolve the issue:

Check that you have the latest version of InaSAFE installed - you may have encountered a bug that is fixed in a subsequent release.
Check the InaSAFE documentation to see if you are trying to do something unsupported.
Report the problem using the issue tracker at https://github.com/AIFDR/inasafe/issues. Reporting an issue requires that you first create a free account at http://github.com. When you report the issue, please copy and paste the complete contents of this panel into the issue to ensure the best possible chance of getting your issue resolved.
Try contacting one of the InaSAFE development team by sending an email to info@inasafe.org. Please ensure that you copy and paste the complete contents of this panel into the email.
Details

These additional details were reported when the problem occurred.

An exception occurred when running the impact analysis.
unpack requires a string argument of length 4 Aggregation error occurred
Diagnostics

In file "C:/Users/kurnia/.qgis2/python/plugins\inasafe\safe\impact_functions\base.py", line 678, in run_analysis self._run_aggregator()
In file "C:/Users/kurnia/.qgis2/python/plugins\inasafe\safe\impact_functions\base.py", line 1335, in _run_aggregator self.aggregator.aggregate(self.impact)
In file "C:/Users/kurnia/.qgis2/python/plugins\inasafe\safe\impact_statistics\aggregator.py", line 591, in aggregate self._aggregate_raster_impact(qgis_impact_layer)
In file "C:/Users/kurnia/.qgis2/python/plugins\inasafe\safe\impact_statistics\aggregator.py", line 739, in _aggregate_raster_impact zonal_statistics = calculate_zonal_stats(impact_layer, self.layer)
In file "C:/Users/kurnia/.qgis2/python/plugins\inasafe\safe\impact_statistics\zonal_stats.py", line 193, in calculate_zonal_stats no_data)
In file "C:/Users/kurnia/.qgis2/python/plugins\inasafe\safe\impact_statistics\zonal_stats.py", line 451, in precise_stats values = struct.unpack('f', scanline) # tuple returned
```

**Comment by ismailsunni** [comment] 2016-05-12 03:22
ok @samnawi  I will check it.
So, the only problem now is volcano polygon with aggregation, right? For both master and develop?

I see that there are difference problem for difference IF if I read @felix-yew 's comment

**Comment by timlinux** [comment] 2016-05-12 07:40
I would like to suggest trying to use QGIS built in Zonal Stats as a first diagnostic. If it works ok, maybe we can remove our home grown Zonal Stats and just use the native one.

**Comment by samnawi** [comment] 2016-05-12 09:47
Yeah @timlinux, It's works
![image](https://cloud.githubusercontent.com/assets/8871958/15210524/14d00988-1861-11e6-9684-86f6038dc7c7.png)

**Comment by ismailsunni** [comment] 2016-05-25 06:26
@samnawi 
I have removed python zonal stat in PR #2833, perhaps we can close this since the problem is caused by python zonal stat.
I will close this, feel free to reopen if you still find the problem.

**Closed by ismailsunni** 2016-05-25 06:26 UTC
Labels: Bug, In progress, Regression
