### ISSUE TITLE
[BUG] The detail of aggregation in tsunami scenario (tsunami raster and building) is not working

### ISSUE THREAD

**Issue by raniedwianugrah** [inasafe/inasafe#2814] opened 2016-05-20 08:21 UTC
### Problem

When we ran the tsunami scenario in InaSAFE Dock and IFCW using the building, tsunami hazard raster, and Maumere village boundary data. Then the analysis result is not showing the detail of aggregation for Maumere Village administrative according to the set analysis area. 

![bug_tsunami_building_2](https://cloud.githubusercontent.com/assets/2528195/15421492/ca632e8c-1e9d-11e6-9490-e3fcd382d13d.PNG)

The result is 'unknown'.

![bug_tsunami_building_3](https://cloud.githubusercontent.com/assets/2528195/15421507/e002b65e-1e9d-11e6-8bdd-65ec0269d115.PNG)

### Environment

InaSAFE 3.4.0 dev-master
QGIS 2.8.9
Windows 7 32 bit/64 bit
Windows 10 64 bit 

### Data Used

1. Maumere_Tsunami_Mw8.1_WGS84.tif
2. Maumere_Building_WGS84.shp
3. Maumere_Village_Boundary_WGS84.shp

**Comment by ismailsunni** [comment] 2016-05-31 08:28
Mine is working like this:
<img width="1279" alt="screen shot 2016-05-31 at 15 28 02" src="https://cloud.githubusercontent.com/assets/1421861/15668212/49982546-2744-11e6-9d09-ef5c9c1154e9.png">

See the breakdown per village

**Comment by lucernae** [comment] 2016-05-31 08:34
I was using 2.14, and also got the the breakdown per village.
by the way, @ismailsunni are you using flood on roads? The issue is for Tsunami on building.

<img width="1440" alt="screen shot 2016-05-31 at 15 33 15" src="https://cloud.githubusercontent.com/assets/831865/15668362/17845ff6-2745-11e6-9f39-a787a027c83f.png">

**Comment by ivanbusthomi** [comment] 2016-05-31 08:36
I got the same result as mas @lucernae too. no problem with me in 2.14.1
![capture](https://cloud.githubusercontent.com/assets/7351977/15668437/6f348b4a-2745-11e6-9172-4ff054907041.PNG)

**Comment by raniedwianugrah** [comment] 2016-05-31 09:12
It's working, I ran in QGIS 2.14.3 32 bit, finally 

![bug_tsu](https://cloud.githubusercontent.com/assets/2528195/15669364/3ac00c04-274a-11e6-853c-ac922c957186.PNG)

**Comment by Gustry** [comment] 2016-05-31 14:59
Thanks for the feedback @raniedwianugrah, if it's working, I'm closing this one.

**Closed by Gustry** 2016-05-31 14:59 UTC
Labels: Ready, Regression
