### ISSUE TITLE
Unable to generate keywords for population raster using Keywords wizard

### ISSUE THREAD

**Issue by NyakudyaA** [inasafe/inasafe#4087] opened 2017-04-06 12:57 UTC
### Problem
When using a population raster published by facebook I am not able to assign keywords using the Keywords wizard. I am however able to generate keywords using the IF wizard

![sa1](https://cloud.githubusercontent.com/assets/2510900/24754872/6605103a-1ad8-11e7-8db8-003a263e36cb.gif)

### Expected Behaviour
Asign keywords using both wizards

### Environment
* InaSAFE : 4.0.1
* QGIS : 2.18.5
* OS : Ubuntu 16.04
* Data used (filenames and paths so as to reproduce, a project is better):
  * Exposure : Population raster for  South Africa from [SA population](https://ciesin.columbia.edu/data/hrsl/#data)
  * Hazard : 
  * Aggregation :
  * Extent : 
  
Checklist (if applicable): 
* [ ] Did you try to run it in debug mode ?
* [ ] Is the data available ?
  * If yes online 

### Proposed Solution
Make all wizards happy

**Comment by Gustry** [comment] 2017-04-06 13:10
This is a duplicate of #3448. I'm going to copy/paste the content of this ticket here and close the old one.

### Problem

from @vdeparday:

Facebook just released the data that we had access to under NDA for the 5 countries above and it is available through CIESIN: https://ciesin.columbia.edu/data/hrsl/ and the announce of the release:https://code.facebook.com/posts/596471193873876/open-population-datasets-and-open-challenges/ (some other press coverage: https://techcrunch.com/2016/11/15/facebook-supports-ngos-with-release-of-emerging-markets-population-data/ and https://www.engadget.com/2016/11/15/facebook-population-maps-open-source/ )
 
It should be a great exposure data (hopefully better than Worldpop and LandScan but some experts were criticizing the methodology so I don’t know what the verdict is). We will make sure it works with InaSAFE. They have other countries such as Vietnam that they have not released officially yet. We can ask for it if you need for a specific project.
 
Another plan would be to create image services with this data to help guide OSM data collection too.


### Expected Behaviour

We should test and validate the the data works well, and possibly think of having a downloader tool to help fetching the data from within QGIS/InaSAFE.

**Comment by ismailsunni** [comment] 2017-04-13 05:08
Checking at the code, this is the one that caused the problem:

```
    def layer_changed(self, layer):
        """Enable or disable keywords editor icon when active layer changes.

        :param layer: The layer that is now active.
        :type layer: QgsMapLayer
        """
        if not layer:
            self._disable_keyword_tools()
            return
        if not hasattr(layer, 'providerType'):
            self._disable_keyword_tools()
            return
        if layer.providerType() == 'wms':
            self._disable_keyword_tools()
            return
        if is_raster_layer(layer) and layer.bandCount() > 1:
            self._disable_keyword_tools()
            return

        self.action_keywords_wizard.setEnabled(True)
```

It seems your layer has more than one band. So, it's not enabled. There is an issue for this problem: https://github.com/inasafe/inasafe/issues/3505

**Comment by ismailsunni** [comment] 2017-10-09 08:21
Fixed. InaSAFE now supports multiband layer.

**Comment by Gustry** [comment] 2017-10-09 08:23
So can we close it if @NyakudyaA confirms?

**Comment by NyakudyaA** [comment] 2017-10-09 08:28
@Gustry I can confirm it works properly now.

**Closed** 2017-10-09 08:29 UTC
Labels: Bug, Candidate for closing, Feature request
