### ISSUE TITLE
QGIS 2.14: some problems to analyst the Tsunami IF

### ISSUE THREAD

**Issue by felix-yew** [inasafe/inasafe#2720] opened 2016-04-12 10:17 UTC
### Problem
Error to run roads impact function for tsunami IF.

I have to tested the road data in Ambon from OSM. When I try to run analysis, an error occured.
![eror2](https://cloud.githubusercontent.com/assets/13621886/14456786/e2d67c0c-00d0-11e6-9653-a30bec4f369a.png)

### Data sample
https://drive.google.com/folderview?id=0B331jyeL4DkVWXg1ZWNEd1ZWaUU&usp=sharing (you can choose osm_road)

### Environment
Windows 7 64 Bit
RAM 8 GB
QGIS 2.14 Essen
InaSAFE 3.3.1

### Proposed Solution
Make it happy

**Comment by samnawi** [comment] 2016-04-12 10:22
I also got the same problem fro this issue when I ran it at InaSAFE 3.3.1.
But, when I try to downgrade to InaSAFE 3.2.6, the IF could run very well.
![image](https://cloud.githubusercontent.com/assets/8871958/14457164/e0f53778-00d2-11e6-8dd5-71320b45feae.png)


Whether this issue has occurred because the new feature in Tsunami IF? 


### CC
@ismailsunni @timlinux @fredychandra

**Comment by Gustry** [comment] 2016-04-12 11:23
Is it possible to share with us the hazard layer?
As I don't have any raster on that area, the IF doesn't run because my layers doesn't overlap.

FYI, Github now accepts zip file in each comment with a drag&drop.

**Comment by felix-yew** [comment] 2016-04-12 14:01
Sorry, I forgot to attach the Hazard. Here it is:

[Hazard_Ambon.zip](https://github.com/inasafe/inasafe/files/215142/Hazard_Ambon.zip)

Thank you.

**Comment by zeppyshiddiq** [comment] 2016-04-14 17:49
Hi All, 

I've also got same problem, for temporary until fixes i use below method.
- Add manually Road_Class_Field in keyword xml generated by Keyword Creation Wizard, in line 233 
![image](https://cloud.githubusercontent.com/assets/10391199/14537589/d11bd6a6-02a1-11e6-81b2-9aec09989927.png)
and replace line 197.

Keyword xml generated from OSM downloader is perfect

- Change CRS of all layers to EPSG:3857, WGS 84/Pseudo Mercantor

![screen shot 04-15-16 at 12 02 am](https://cloud.githubusercontent.com/assets/10391199/14537223/477936ce-02a0-11e6-9339-cd493fdd275f.PNG)

**Comment by ismailsunni** [comment] 2016-04-19 02:06
Hi @felix-yew and @samnawi 
I have made a fix in #2729. 
The problem is the IF has wrong metadata. Previously, it was `structure_class_field` and I have changed it to `road_class_field`.
You need to re-assign the keywords for the road layer, then you can run it as before again.

**Comment by ismailsunni** [comment] 2016-04-20 00:49
Checked by @felix-yew and @ivanbusthomi. Released in 3.3.2. Closing this.

**Closed by ismailsunni** 2016-04-20 00:49 UTC
Labels: Bug, In progress
