### ISSUE TITLE
BUG : Could not compute using BIG (Indonesia Geospatial Agency) data

### ISSUE THREAD

**Issue by samnawi** [inasafe/inasafe#2369] opened 2015-09-16 08:13 UTC
# Problem
I try to use the official data for basemap from BIG. I get the data from this link http://portal.ina-sdi.or.id/.
When I try to run with this data, in the detailed report, InaSAFE says that could not compute the road type report. Whereas, when I use OSM data, the detailed report is appear.
I found the bug in tsunami also flood hazard VS roads.

# Detail
Using BIG data
![selection_200](https://cloud.githubusercontent.com/assets/8871958/9899560/e826d2ce-5c84-11e5-9bd5-da6137e4fd0e.png)

Using OSM Data
![selection_201](https://cloud.githubusercontent.com/assets/8871958/9899565/f226633e-5c84-11e5-9758-4a23609f2502.png)

# Data
Hazard : Jakarta Flood Data and Tsunami Maumere
Exposure : OSM Roads and BIG Roads

# PC Platform
Linux Ubuntu 14.04
QGIS 2.8.3
InaSAFE 3.2.0.dev-cdfcacc

# Proposed Solution
Make it happy.

# CC
@Charlotte-Morgan @fredychandra @timlinux 

Thank you

**Comment by Charlotte-Morgan** [comment] 2016-03-10 08:32
handing this over to you @Gustry - it is a similar issue to other road tickets #2361

**Comment by timlinux** [comment] 2016-03-10 08:41
@Gustry We need to remove all the nasty hard coded type stuff in the aggregators. In the long term we want to move this logic into the IF main run loop and only iterate once.

For the short term I would like to propose that we do this:

Modify both ``safe/postprocessors/building_type_postprocessor.py`` and ``safe/postprocessors/road_type_postprocessor.py``  to use a utility function (we have it already somewhere) that replaces logic like this:

```
        self.fields_values = OrderedDict([
            ('Medical', ['Clinic/Doctor', 'Hospital']),
            ('Schools', ['School', 'University/College', ]),
            ('Places of worship', [
                'Place of Worship - Unitarian',
                'Place of Worship - Islam',
                'Place of Worship - Buddhist',
                'Place of Worship']),
            ('Residential', ['Residential']),
            ('Government', ['Government']),
            ('Public Building', ['Public Building']),
            ('Fire Station', ['Fire Station']),
            ('Police Station', ['Police Station']),
            ('Supermarket', ['Supermarket']),
            ('Commercial', ['Commercial']),
            ('Industrial', ['Industrial']),
            ('Utility', ['Utility']),
            ('Sports Facility', ['Sports Facility']),
            ('Other', [])])
```

With a simple dictionary which is computed from a table scan.

A couple of downsides of this approach:

* no sorting in a logical sequence (e.g. putting hospitals first in the list)
* may have inconsistent data in the attribute table resulting in e.g. **Hospital**, and **hospital** which show up as  separate classes (we could do some basic logic to deal with simple cases)

In the longer term we need to have class mappings done in the layer metadata and set by the user during run of the keywords wizard, and then read the mappings from there.

**Comment by timlinux** [comment] 2016-03-10 08:44
@Gustry ok I chatted more to @Charlotte-Morgan - I think we must rather work straight away on the 'proper' solution - let the user do concept mappings in the keywords wizard and read from that.

**Comment by timlinux** [comment] 2016-03-10 08:46
So in the wizard we will have a screen where they users maps the different unique classes to known concepts (Medical, Religious) etc. That metadata would then be read by the aggregation logic to determine how to group things.

**Comment by Gustry** [comment] 2016-04-26 04:41
Work in progress in t the PR https://github.com/inasafe/inasafe/pull/2743

**Comment by Gustry** [comment] 2016-04-26 06:28
This seems to be a duplicate of https://github.com/inasafe/inasafe/issues/2370

**Comment by Gustry** [comment] 2016-05-16 04:13
The PR #2743 has been merged. I'm closing this issue.

**Closed by Gustry** 2016-05-16 04:13 UTC
Labels: Bug, Ready
