### ISSUE TITLE
TypeError when running Flood vector on Population vector

### ISSUE THREAD

**Issue by ivanbusthomi** [inasafe/inasafe#4200] opened 2017-05-23 09:58 UTC
### Problem
When I tried running flood vector on population vector, I got this error message
```
Problem
The following problem(s) were encountered whilst running the analysis.
TypeError

Details
These additional details were reported when the problem occurred.
unhashable type: 'list'

Diagnostics
In file "C:/Users/busthi/.qgis2/python/plugins\inasafe\safe\impact_function\impact_function.py", line 1083, in run self._run()
In file "C:/Users/busthi/.qgis2/python/plugins\inasafe\safe\utilities\profiling.py", line 122, in with_profiling ret = fn(*args, **kwargs)
In file "C:/Users/busthi/.qgis2/python/plugins\inasafe\safe\impact_function\impact_function.py", line 1244, in _run self.gis_overlay_analysis()
In file "C:/Users/busthi/.qgis2/python/plugins\inasafe\safe\utilities\profiling.py", line 122, in with_profiling ret = fn(*args, **kwargs)
In file "C:/Users/busthi/.qgis2/python/plugins\inasafe\safe\impact_function\impact_function.py", line 1357, in gis_overlay_analysis self.hazard_preparation()
In file "C:/Users/busthi/.qgis2/python/plugins\inasafe\safe\utilities\profiling.py", line 122, in with_profiling ret = fn(*args, **kwargs)
In file "C:/Users/busthi/.qgis2/python/plugins\inasafe\safe\impact_function\impact_function.py", line 1715, in hazard_preparation self.debug_layer(self.hazard)
In file "C:/Users/busthi/.qgis2/python/plugins\inasafe\safe\impact_function\impact_function.py", line 1036, in debug_layer check_inasafe_fields(layer)
In file "C:/Users/busthi/.qgis2/python/plugins\inasafe\safe\gis\sanity_check.py", line 33, in check_inasafe_fields difference = set(inasafe_fields.values()).difference(real_fields)
```
When I tried updating the keyword of the hazard layer used in this case, the error disappeared, and I got a result. But when I tried updating it again, the error somehow reappeared.

### Expected Behaviour
It can be run without error.

### Environment
* InaSAFE : 4.1.0b0 (develop)
* QGIS : 2.14.10
* OS : Windows
* Data used (filenames and paths so as to reproduce, a project is better):
  * Exposure : [Exposure.zip](https://github.com/inasafe/inasafe/files/1021725/Exposure.zip)
  * Hazard : [Hazard.zip](https://github.com/inasafe/inasafe/files/1021726/Hazard.zip)
  * Aggregation :
  * Extent : 
  
Checklist (if applicable): 
* [ ] Did you try to run it in debug mode ?
* [ ] Is the data available ?
  * If yes,where (BTSync, data.inasafe.org, zip) ? 

### Proposed Solution
Make it happy

---
**CC** : @Charlotte-Morgan @timlinux @samnawi @felix-yew @ismailsunni @Gustry

**Comment by samnawi** [comment] 2017-05-23 10:19
I got this problem tomorrow, but when I re-keyword the file, It's run properly

**Comment by ismailsunni** [comment] 2017-05-23 10:59
Hi @ivanbusthomi @samnawi 

I have found the problem.

Its because the InaSAFE fields that's not exist in the actual layer. In your case, your hazard layer has `M_65_Plus` field in the keywords as `Elderly count`, but the layer itself doesn't have the fields.

The problem is (99%) caused by the keyword wizard. I think it was like this:
1. You run keyword wizard for exposure layer. It has field mapping tool step. Finish.
2. Then you run keyword wizard for hazard layer. It doesn't show field mapping tool step. But for some reason, the previous instance of field mapping step is still alive. Then when we finish our keyword wizard, it will also write some inasafe fields from the field mapping tool step.
3. The hazard layer doesn't have proper keywords, and it will get an error like above if you run the analysis.

Solution:
1. Fix the keywords wizard. After the fixed has been merged, we need to rerun the keyword wizard for the layer with broken keywords (@ismailsunni)
2. Check if the layer has good metadata, i.e. it has inasafe fields that really exists in the attribute tables. There is also a case where someone change or deleted a field, so the keyword is not good anymore. (@gustry)

**Comment by Gustry** [comment] 2017-05-23 11:43
I'm working on solution 2 in the PR above.

> I got this problem tomorrow, but when I re-keyword the file, It's run properly

@ivanbusthomi Thanks for reporting issues for tomorrow !

**Comment by ismailsunni** [comment] 2017-05-23 15:09
@Gustry it is @samnawi not @ivanbusthomi :D

**Comment by Gustry** [comment] 2017-05-24 03:43
I'm keeping this ticket for me

**Comment by ismailsunni** [comment] 2017-05-24 04:12
Ah, the commit closed the issue :D

for more context why we keep this ticket https://github.com/inasafe/inasafe/pull/4206#issuecomment-303607647

**Closed** 2017-05-25 03:45 UTC
Labels: Bug
