### ISSUE TITLE
Wizard tests failing

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#2494] opened 2015-12-03 03:27 UTC
Hi @borysiasty 

Although the wizard test passed with your last merge, I regularly get these when testing on my local machine (against current develop fd68360a84eb160f58027bc3bfe593feeacef39c):

```
Failure
Traceback (most recent call last):
  File "/Users/timlinux/dev/python/inasafe/safe/gui/tools/test/test_wizard_dialog.py", line 668, in test_existing_complex_keywords
    self.assertEqual(dialog.leSource.text(), source, message)
AssertionError: Source should be Source
```

and

```
Failure
Traceback (most recent call last):
  File "/Users/timlinux/dev/python/inasafe/safe/gui/tools/test/test_wizard_dialog.py", line 406, in test_keywords_creation_wizard
    self.assertEqual(keywords, expected_keywords, message)
AssertionError: Invalid metadata!
 Was: {'hazard_category': 'single_event', 'keyword_version': 3.2, 'title': 'Flood Polygon', 'hazard': 'flood', 'field': 'FLOODPRONE', 'value_map': {'dry': ['NO'], 'wet': ['YES']}, 'vector_hazard_classification': 'flood_vector_hazard_classes', 'layer_geometry': 'polygon', 'layer_purpose': 'hazard', 'layer_mode': 'classified'}
 Should be: {'hazard_category': 'single_event', 'hazard': 'flood', 'source': 'some source', 'keyword_version': 3.2, 'title': 'some title', 'field': 'FLOODPRONE', 'value_map': {'dry': ['NO'], 'wet': ['YES']}, 'vector_hazard_classification': 'flood_vector_hazard_classes', 'layer_geometry': 'polygon', 'layer_purpose': 'hazard', 'layer_mode': 'classified'}
```

I wanted to do some cleanups to the code here #2492 but I can't integrate them because of these failing tests. Since the tests also fail against current develop I think the failure is not because of my changes but due to something else. Could you take a look please @borysiasty ?

**Comment by timlinux** [comment] 2015-12-03 09:58
Please see https://travis-ci.org/inasafe/inasafe/builds/94575704 for an example

**Comment by borysiasty** [comment] 2015-12-04 09:59
Ok, I'll look at it on Sunday!

**Comment by timlinux** [comment] 2015-12-05 05:21
@borysiasty thanks man - its the highest priority because all of the subsequent PR's to develop are failing

**Comment by borysiasty** [comment] 2015-12-06 22:17
Caused by #2504

**Comment by borysiasty** [comment] 2015-12-07 13:59
I'm closing it as the last build passed the tests.

**Comment by borysiasty** [comment] 2015-12-07 14:00
@timlinux  - ah it seems I have no privileges to close tickets recently.

**Closed** 2015-12-07 15:20 UTC
