### ISSUE TITLE
Impact Function Upgrade to Support InaSAFE Realtime Processor

### ISSUE THREAD

**Issue by lucernae** [inasafe/inasafe#2642] opened 2016-02-24 01:48 UTC
### Problem

Because we had some new data to use for Realtime Shake and Flood, we know that some current impact function is insufficient to handle those data.

### Expected Behaviour

Develop/upgrade/extend new/existing Impact Function to handle these new data

### Proposed Solution

The following combination and condition can't be handled yet:

- [ ] Classified Vector Earthquake - Continuous Vector (Polygon/Point) Population. Used for Realtime Shake. See #2438 #2589 
- [ ] Classified Vector Flood (with dynamic classes) - Continuous Vector (Polygon) Population. Used for Realtime Flood. See #2495 #2497

**Comment by Charlotte-Morgan** [comment] 2016-03-10 10:28
Real time earthquake will not use classified earthquake vector hazard.  Realtime eqrthquake uses continous raster data for a single event.  Most vector hazard data for earthquake is classified multi event. This is not suitable for realtime analysis.

**Comment by timlinux** [comment] 2016-04-21 12:51
Closing this as the issue is not relevant.

**Closed by timlinux** 2016-04-21 12:51 UTC
Labels: Realtime
