### ISSUE TITLE
Assertion Error - earthquake raster on population raster

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#3719] opened 2017-01-27 10:02 UTC
### Problem
The InaSAFE analysis stops with an assertion error and writes a DEBUG folder (empty) when not in debug mode
### Expected Behaviour
InaSAFE analysis will run and be happy with no error

### Environment
* InaSAFE : 4.0.0b0
* QGIS : 2.14.0
* OS : windows
* Data used :
  * Exposure : Aceh population raster
  * Hazard : Pidie Earthquake
  * Aggregation : none

### Error Message
Problem

The following problem(s) were encountered whilst running the analysis.

AssertionError
Suggestion

You can try the following to resolve the issue:

Check that you have the latest version of InaSAFE installed - you may have encountered a bug that is fixed in a subsequent release.
Check the InaSAFE documentation to see if you are trying to do something unsupported.
Report the problem using the issue tracker at https://github.com/inasafe/inasafe/issues. Reporting an issue requires that you first create a free account at http://github.com. When you report the issue, please copy and paste the complete contents of this panel into the issue to ensure the best possible chance of getting your issue resolved.
Try contacting one of the InaSAFE development team by sending an email to info@inasafe.org. Please ensure that you copy and paste the complete contents of this panel into the email.
Diagnostics
```
In file "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\impact_function\impact_function.py", line 977, in run self._run()
In file "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\utilities\profiling.py", line 93, in with_profiling ret = fn(*args, **kwargs)
In file "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\impact_function\impact_function.py", line 1124, in _run self.damage_curve_analysis()
In file "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\utilities\profiling.py", line 93, in with_profiling ret = fn(*args, **kwargs)
In file "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\impact_function\impact_function.py", line 1226, in damage_curve_analysis self.earthquake_raster_population_raster()
In file "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\utilities\profiling.py", line 93, in with_profiling ret = fn(*args, **kwargs)
In file "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\impact_function\impact_function.py", line 1254, in earthquake_raster_population_raster self.hazard.extent())
In file "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\utilities\profiling.py", line 93, in with_profiling ret = fn(*args, **kwargs)
In file "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\gis\raster\rasterize.py", line 83, in rasterize_vector_layer assert layer_aligned.isValid()
```
### Proposed Solution
make it happy

**Comment by Gustry** [comment] 2017-01-30 21:37
This should be fixed in #3669

I guess you were using QGIS 2.14.

**Comment by Gustry** [comment] 2017-02-01 09:44
New error from this morning using Aceh scenario : 
```
Problem

The following problem(s) were encountered whilst running the analysis.

ValueError
Suggestion

You can try the following to resolve the issue:

Check that you have the latest version of InaSAFE installed - you may have encountered a bug that is fixed in a subsequent release.
Check the InaSAFE documentation to see if you are trying to do something unsupported.
Report the problem using the issue tracker at https://github.com/inasafe/inasafe/issues. Reporting an issue requires that you first create a free account at http://github.com. When you report the issue, please copy and paste the complete contents of this panel into the issue to ensure the best possible chance of getting your issue resolved.
Try contacting one of the InaSAFE development team by sending an email to info@inasafe.org. Please ensure that you copy and paste the complete contents of this panel into the email.
Details
These additional details were reported when the problem occurred.

cannot convert float NaN to integer
Diagnostics

In file "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\impact_function\impact_function.py", line 981, in run self._run()
In file "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\utilities\profiling.py", line 93, in with_profiling ret = fn(*args, **kwargs)
In file "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\impact_function\impact_function.py", line 1128, in _run self.damage_curve_analysis()
In file "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\utilities\profiling.py", line 93, in with_profiling ret = fn(*args, **kwargs)
In file "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\impact_function\impact_function.py", line 1230, in damage_curve_analysis self.earthquake_raster_population_raster()
In file "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\utilities\profiling.py", line 93, in with_profiling ret = fn(*args, **kwargs)
In file "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\impact_function\impact_function.py", line 1273, in earthquake_raster_population_raster exposed, self.aggregation, earthquake_function())
In file "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\utilities\profiling.py", line 93, in with_profiling ret = fn(*args, **kwargs)
In file "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\impact_function\earthquake.py", line 363, in make_summary_layer int(mmi_exposed * fatality_rate[mmi])) # rounding down
```

**Comment by Gustry** [comment] 2017-02-01 16:37
The issue is from the align raster tools I think. I need to check if it comes from qgis core or from inasafe.

**Comment by Gustry** [comment] 2017-02-23 06:49
This should have been fixed. I'm going to close this one.

**Closed by Gustry** 2017-02-23 06:49 UTC
Labels: Bug, Current sprint, Release Blocker
