### ISSUE TITLE
Building Type Report Table mixing with zero and no data

### ISSUE THREAD

**Issue by fredychandra** [inasafe/inasafe#2318] opened 2015-09-03 08:55 UTC
# Problem

The Building Type Report Table still reporting zero (o) and No data if run IF with aggregation. The implication is the report become too long and truncation in the lateral side. 
The table still use OSM preset/attribute although the exposure data that being used is not come from OSM downloader.

![image](https://cloud.githubusercontent.com/assets/6345285/9654691/922c2e92-5256-11e5-9999-2cbaafe2aa6b.png)

![image](https://cloud.githubusercontent.com/assets/6345285/9654429/ee50ca5e-5254-11e5-84ce-ac641ae628da.png)

![image](https://cloud.githubusercontent.com/assets/6345285/9654563/d015a522-5255-11e5-9573-737c3b7b31e9.png)

# Detail

Test on Dock IF : Earthquake with Building Point
Hazard Data      : EQ_TTU (Polygon)
Exposure           : Infrastuvture_BIG (Point)
Aggregation       : Yes (Village Level)

# proposed solution
1. No need report the zero (0) result. This can save space
2. The Detail Building Type report should use existing exposure that run in IF

# CC 
@ismailsunni @samnawi @Charlotte-Morgan

**Comment by Charlotte-Morgan** [comment] 2015-09-03 09:32
see #2320

**Comment by Charlotte-Morgan** [comment] 2015-09-03 10:38
HI @fredychandra
i agree - if there is a total of 0 for any type the type can be removed
and if all values in a table are 0 or nodata - do not write the table

**Comment by cchristelis** [comment] 2015-09-04 07:51
Hi @fredychandra, i am unfortunately unable to reproduce with the test data. Is there a way to get the exact scenario to me? Perhaps even just a representative clip of the data?

**Comment by cchristelis** [comment] 2015-09-04 07:57
Yeah, the post processors seem to be written with only OSM building types in mind: 
`
self.fields_values = OrderedDict([
            ('Medical', ['Clinic/Doctor', 'Hospital']),
            ('Schools', ['School', 'University/College', ]),
            ('Places of worship', ['Place of Worship - Unitarian',
                                   'Place of Worship - Islam',
                                   'Place of Worship - Buddhist',
                                   'Place of Worship']),
            ('Residential', ['Residential']),
            ('Government', ['Government']),
            ('Public Building', ['Public Building']),
            ('Fire Station', ['Fire Station']),
            ('Police Station', ['Police Station']),
            ('Supermarket', ['Supermarket']),
            ('Commercial', ['Commercial']),
            ('Industrial', ['Industrial']),
            ('Utility', ['Utility']),
            ('Sports Facility', ['Sports Facility']),
            ('Other', [])])
`

**Comment by fredychandra** [comment] 2015-09-04 08:19
HI @cchristelis i used these data : 
1. TTU_Earthquake.shp (Polygon) as Hazard
2. TTU_Infrastucture_BIG.shp as exposure (Non OSM data set)
3. TTU_Villagge_BIG.shp as aggregation layer

Please find the data that I have used for the test (IF : EQ Polygon with Point with Aggregation) on the link below.

https://drive.google.com/drive/folders/0B_gC8poAYEtefmxrMnRZdGQ5bl8xeHhVVlE4Y2J6T3N4aXVCMl9PcEFjbXZIb2lZQzBmNEU

**Comment by cchristelis** [comment] 2015-09-09 08:40
The no data / zero column removal has been added in #2345. The underlying issue is caused by non- osm data, which is not handled in the post processors.

**Comment by cchristelis** [comment] 2015-09-09 08:41
This issue should be moved to #2332.

**Comment by Charlotte-Morgan** [comment] 2015-09-17 03:44
this relates to non OSM data - lets look at this for 3.3
Milestone and label updated

**Comment by ismailsunni** [comment] 2016-01-04 07:57
hi @fredychandra 
Can you re-share your data above? I try to find it, but the link is no longer valid.

Thanks

**Comment by felix-yew** [comment] 2016-05-24 11:24
Hi @ismailsunni we have compiled a check list about Zero and No Data, too. Here is the link

https://drive.google.com/file/d/0B05hpjhYVKxga1AwMGpOLW05cFk/view?usp=sharing

The information about the Impact Function Table of Sequence Order:
"V" it means the sequence may appear in map legend and/or table analysis, and needs fixing.
"-" it means already good.

Make it happy :smile: 

Cc: @Charlotte-Morgan @timlinux @samnawi @ivanbusthomi

**Comment by timlinux** [comment] 2016-08-08 08:28
This should be fixed with the value mapping. @ismailsunni please confirm and close

**Comment by ismailsunni** [comment] 2016-08-08 10:39
Closed. Fixed in #2904 by @Gustry

**Closed by ismailsunni** 2016-08-08 10:39 UTC
Labels: Aggregation, Current sprint, Postprocessing
