### ISSUE TITLE
BUG : There is no option available in "Might" (Flood Polygon & Structure Point)

### ISSUE THREAD

**Issue by samnawi** [inasafe/inasafe#2278] opened 2015-08-28 09:48 UTC
# Problem
I can not run the IF using Flood polygon and Structure point, because there is no option available in part of "Might" 
![selection_155](https://cloud.githubusercontent.com/assets/8871958/9543593/2b6dbb78-4da4-11e5-8ed6-c7a440841336.png)

# Platform
Ubuntu 14.04 64-Bit
QGIS 2.8.3
InaSAFE 3.2.0.dev-4890424

# Proposed Solution
Make it happy, appear the option for this IF

# CC
@timlinux @Charlotte-Morgan 

Thank you

**Comment by ismailsunni** [comment] 2015-08-28 10:16
Can you paste here the keywords of both exposure and hazard?

Currently, we don't have specific IF for flood polygon vs building point. But we have generic IF for polygon hazard vs building point. But you need to assign generic classes for the hazard layer.

**Comment by samnawi** [comment] 2015-08-28 10:36
@ismailsunni I look it in the IFCW, there is spesific IF for flood polygon vs Building
![selection_156](https://cloud.githubusercontent.com/assets/8871958/9544431/eb9dea02-4daa-11e5-9b5c-714496b4e9cf.png)
Is the function just for High, Medium, Low classification?

Actually I use the data, same with the data in this link http://data.inasafe.org/InaSAFE%203.1%20Training%20Data/DKI%20Jakarta.zip.

This is the keyword for the hazard data
date: 18 January 2013
field: FLOODPRONE
hazard: flood
hazard_category: single_event
keyword_version: 3.2
layer_geometry: polygon
layer_mode: classified
layer_purpose: hazard
source: OSM & BPBD DKI Jakarta
title: A Flood in Jakarta like 2013
value_map: {"dry": ["NO"], "wet": ["YES"]}
vector_hazard_classification: flood_vector_hazard_classes

**Comment by ismailsunni** [comment] 2015-08-28 10:43
Hi @samnawi 
What I mean with specific IF is IF like FloodPolygonBuildingFunction. If you see under the table, there is available function : Classified polygon hazard on buildings. It's a generic IF, not a specific one.

And based on you keywords, the `vector_hazard_classification` has value `flood_vector_hazard_classes`. So, it won't be recognized by the Classified polygon hazard on buildings. You need to assign the `vector_hazard_classification` to  generic vector hazard classes.

The generic IF sometimes helps, but sometimes confusing. We have this discussion when we were in Jakarta, and perhaps we can have another one next month

**Comment by samnawi** [comment] 2015-08-28 10:48
OK @ismailsunni , Sorry about it, I'm not notice about the available function. Maybe we can pending this stuff until we will meet when you come in Jakarta next month.

Thank you.

**Comment by adissadis** [comment] 2015-09-30 08:01
@ismailsunni this issue still occured when i tried to run InaSAFE for Building Points and also in the IFCW i can still access the building points for flood vector hazard.

![image](https://cloud.githubusercontent.com/assets/2520159/10187648/1052dbb2-6784-11e5-9a5b-b72364445d6c.png)

**Comment by ismailsunni** [comment] 2015-10-01 04:36
@adissadis 
can you paste here the keywords of both hazard and exposure layers?

**Comment by adissadis** [comment] 2015-10-01 06:58
```
The following keywords are defined for the active layer:
Title	Building centroids
Purpose	exposure
Exposure	structure
Geometry	Point
Data type	classified
Attribute field	TYPE
Source	OpenStreetMap - www.openstreetmap.org
Url	www.openstreetmap.org
License	Open Data Commons Open Database License (ODbL)
Date	July 2015
Keyword version	3.2
```

```
The following keywords are defined for the active layer:
Title	A Flood in Jakarta like 2013
Purpose	hazard
Hazard	flood
Scenario	Single event
Geometry	polygon
Data type	classified
Classes	This is a binary description for an area. The area is either wet (affected by flood water) or dry (not affected by flood water). This unit does not describe how wet or dry an area is.
Attribute field	FLOODPRONE
Attribute value map	
dry	NO
wet	YES
Source	OSM & BPBD DKI Jakarta
Date	18 January 2013
Keyword version	3.2
```

**Comment by samnawi** [comment] 2015-12-11 02:50
@ismailsunni Is this ticket is already fix? Because I can do this IF now.
![selection_001](https://cloud.githubusercontent.com/assets/8871958/11734737/87d0d720-9fec-11e5-915b-43907d0db236.png)

**Comment by ismailsunni** [comment] 2015-12-15 04:03
Hi @samnawi 

I think this ticket is already fixed (or actually, the problem is caused by wrong keywords for the hazard layer). So, it's not a bug. I will close this, and if anyone has a similar problem can re-open it.

**Closed by ismailsunni** 2015-12-15 04:03 UTC
Labels: Bug, Ready
