### ISSUE TITLE
[BUG] Population not counted in affected area for Raster Flood Hazard

### ISSUE THREAD

**Issue by adissadis** [inasafe/inasafe#2531] opened 2015-12-22 04:57 UTC
# Problem
Hi @timlinux 

I ran InaSAFE analysis using Population and Flood Raster HKV and found that in several area, even those area is affected by flood, InaSAFE didn't analyze and count the numbers of people in those area. 

 

![image](https://cloud.githubusercontent.com/assets/2520159/11948033/8e51d672-a8a1-11e5-829c-a08a035a0daa.png)

In the screenshot i give above, as you can see at the red box and red arrow, it should have result a number of people who affected by flood, but it show no people affected instead.

![image](https://cloud.githubusercontent.com/assets/2520159/11948059/f3923388-a8a1-11e5-82c2-a16c5ea54fbe.png)

# Specification
This problem appear in 3 laptop that using:
Windows 7 (1 laptop using 32bit, 2 laptop using 64bit) 
QGIS 2.8.4
InaSAFE 3.2.5 dev master (sync with Github at 21 December 2015)

I give you my InaSAFE analysis result in case maybe you need to compare the result with yours:
https://drive.google.com/file/d/0B3X6jqdE4HueV0hOSHdxTFJfWXc/view?usp=sharing

cc: @samnawi

**Comment by samnawi** [comment] 2015-12-29 06:41
Hi @adissadis I get this problem too. Either in WIndows 7 64 bit and Ubuntu 14.04 machine. Using QGIS 2.8.4 and 2.12.1.

![image](https://cloud.githubusercontent.com/assets/8871958/12030476/d0da2702-ae31-11e5-9357-1ad302bd1eea.png)

**Comment by samnawi** [comment] 2016-01-07 11:48
I still curious about this problem, so I tried to calculate using spatial analyst in QGIS.

For add the information :

I tried to calculate this IF for >= 0.5 m, generate 1,918,000 affected population
![selection_040](https://cloud.githubusercontent.com/assets/8871958/12169904/dbdb15be-b56e-11e5-844b-0018d8c8541a.png)


When I tried to polygonize the hazard, and then doing zonal statistics, the result is 2,093,655 people.
![selection_039](https://cloud.githubusercontent.com/assets/8871958/12169539/bec4f61e-b56b-11e5-8500-5f785295c662.png)

**Comment by Charlotte-Morgan** [comment] 2016-01-08 10:28
hi @adissadis and @samnawi 
I get this too. I'm using windows 7, QGIS 2.8.3 and InaSAFE dev 3.3.0 (5db8f80).
I also note the values quoted by @samnawi are alarmingly large and he will write a different ticket.
please note this bug post dates 35a7581 - if that is any help

**Comment by ismailsunni** [comment] 2016-01-11 10:24
hi @adissadis @samnawi can you try it with previous InaSAFE version? For example version 3.2

**Comment by timlinux** [comment] 2016-01-11 11:55
Hi

So here are a couple of thoughts.

![selection_040](https://cloud.githubusercontent.com/assets/8871958/12169904/dbdb15be-b56e-11e5-844b-0018d8c8541a.png)

1) I wonder if the pop cells in the black box were simple excluded during clipping and thus not stats reported.
2) For very small inundated areas against large pop cells, there may simply be a symbology issue - the cells may come out to have >2 population and thus be rendered white? It would be worth investigating (e.g. make the first class in the legend pink or some other easy to see colour.

**Comment by samnawi** [comment] 2016-01-12 04:11
Hi @ismailsunni and @timlinux 

Before I test it in previous InaSAFE version, I get the strange result when test it in 3.3 dev.
Like in the @timlinux repost picture from me in above, There is no result in the black box.
But, this morning, when I try to test it again, the result is appear in the black box area.
![selection_048](https://cloud.githubusercontent.com/assets/8871958/12254356/1137c67c-b91a-11e5-8093-59b1ab79ad75.png)

When I try to zoom in to the random area that seem blue color in that area, then I identify the pixel, the result is like this picture.
![selection_050](https://cloud.githubusercontent.com/assets/8871958/12254387/7269e498-b91a-11e5-87bd-c142cf0b80d0.png)

This occured in both of Windows 7 -and Ubuntu 14.04.

@adissadis Have you test it again and get similar result?

**Comment by adissadis** [comment] 2016-01-12 04:41
@samnawi  I test again with recent update InaSAFE from github and i don't get similar result like @timlinux  in those area.

![image](https://cloud.githubusercontent.com/assets/2520159/12254934/f6236eac-b920-11e5-916b-564190000015.png)

Here's InaSAFE result screenshot:
![image](https://cloud.githubusercontent.com/assets/2520159/12254940/0c243c90-b921-11e5-895b-0e0ed41e374b.png)

**Comment by timlinux** [comment] 2016-01-22 10:40
![selection_005](https://cloud.githubusercontent.com/assets/178003/12508430/8f12c80c-c104-11e5-9ac9-4a9d49b65845.png)

Regarding the block on the right, I did a manual analysis in QGIS and all of the values in the area on the right are under 1m. So it seems normal for me that it does not show any impact there.

**Comment by timlinux** [comment] 2016-01-22 11:00
Hi @samnawi @Charlotte-Morgan and @Gustry 

Etienne and I spent quite a bit of time digging into this. I believe this ticket should be closed as a non-issue unless I am missing something.

1) The Areas pointed to by the arrows is a symbology issue where pop counts < 1 per cell are drawn transparently.
2) The area on the right is a bit strange in the data - there is a very linear cut-off north south in the image where to the west of it the water is 2m and to the right it is < 1m. Perhaps this is due to an engineering feature such as a duct or something. The impact layer seems consistent with the input data here.

So did I miss a nuance here, or can I go ahead and close this ticket.

**Comment by samnawi** [comment] 2016-01-22 11:16
yeah @timlinux I think this issue was fixed. 
It's strange, because some user found this problem, but suddenly the problem is gone when we tried in the other day. 
I just try again this IF, and can work properly.

![image](https://cloud.githubusercontent.com/assets/8871958/12509319/354fd3a2-c134-11e5-8ae8-2731ff7a111e.png)

Thank you.

**Comment by timlinux** [comment] 2016-01-22 11:21
OK @samnawi thanks so much for the feedback, closing this out.

**Closed by timlinux** 2016-01-22 11:21 UTC
Labels: Regression, Release Blocker
