### ISSUE TITLE
Jakarta aggregation data errors

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#3713] opened 2017-01-27 06:31 UTC
### problem
In Version 4.0 the Jakarta district and subdistrict boundary data used for aggregation show up  as being invalid.

### proposed solution
we need to fix the data (using spatial tools - please do not redigitise it!!)

###
make it happy :)

**Comment by Gustry** [comment] 2017-01-27 06:53
For subdistrict, I could have the error easily : 
![screen shot 2017-01-27 at 07 50 53](https://cloud.githubusercontent.com/assets/1609292/22362767/6c5652ea-e465-11e6-80a3-6e36ebb3575c.png)

But for the district layer, the processing tool 'Check validity' says everything is ok 🙁
But the problem is when you use the district layer in inasafe, QGIS can't compute the union.

**Comment by Gustry** [comment] 2017-01-27 07:27
Or should I try to make it valid on runtime ? @timlinux

**Comment by Charlotte-Morgan** [comment] 2017-01-27 10:06
hi @Gustry - this is a ticket to @samnawi to fix the data at this end, nothing for InaSAFE I don't think. Just letting you know we have a problem in the data and that I have not been able to fix it.
QGIS thinks it is invalid but Arc is happy when i run checks and fix. Even when I save and get back into QGIS its still not happy.

**Comment by Gustry** [comment] 2017-01-27 10:13
![screen shot 2017-01-27 at 11 11 03](https://cloud.githubusercontent.com/assets/1609292/22367381/8f01254c-e481-11e6-89ee-4089ee3dc412.png)

**Comment by Charlotte-Morgan** [comment] 2017-01-27 10:14
Yes - I'm sure he will fix it - or talk to the custodians

**Comment by timlinux** [comment] 2017-01-27 22:08
@Charlotte-Morgan these data have been broken since I can remember - I always left it like that because its an imperfect world and working with a bit of ropey data is a better reflection of how our users are probably working. I think the onus should be on us to either report these issues to the user, or deal with them seamlessly where we can....

Anyway happy to be overridden on this if you want to have clean data rather.

**Comment by timlinux** [comment] 2017-01-27 22:10
BTW when I investigated the data before it had interior rings that comprised only two vertices iirc. If you want to fix it I suggest using a tiny buffer and then a tiny inverse buffer - it will dissolve the interior rings.

**Comment by samnawi** [comment] 2017-02-02 02:38
OK @Charlotte-Morgan I'll try to looking up the problem and fix it.

**Comment by samnawi** [comment] 2017-02-08 06:30
Hi @Charlotte-Morgan I already fix the problem, and put it in the minion testing data

**Comment by Gustry** [comment] 2017-02-08 06:36
Hi @samnawi Where is the minion testing data ?
I often use this link but DKI Jakarta is not updated yet : http://data.inasafe.org/InaSAFE%203.5%20Training%20Data/
or is-it in BTSync ?

**Comment by samnawi** [comment] 2017-02-13 08:20
Hi @Gustry I just put in the real world data

**Comment by Gustry** [comment] 2017-02-13 08:33
Thanks, I see BTSync is syncing. I will try.

**Comment by Gustry** [comment] 2017-02-22 07:11
According to @Charlotte-Morgan this issue has not been fixed and it's a release blocker : [February 22, 2017 1:08 AM](https://gitter.im/inasafe/inasafe?at=58acd66d872fc8ce626896b7)

**Comment by Gustry** [comment] 2017-02-22 09:25
![buffers](https://cloud.githubusercontent.com/assets/1609292/23205139/15eb1a9c-f8e9-11e6-9e2d-4618c8d215c3.gif)

Very strange, even if I create a buffer of 0, one feature is dropped.

**Comment by Gustry** [comment] 2017-02-22 09:54
I made a PR to fix geometries on the fly.

**Comment by samnawi** [comment] 2017-02-23 05:06
Hi @gustry So, it's should already be fixed?

**Comment by Gustry** [comment] 2017-02-23 06:47
Yes, it has been merged to develop. Feel free to reopen if you still have an issue.

**Closed by Gustry** 2017-02-23 06:47 UTC
Labels: Release Blocker
