### ISSUE TITLE
AttributeError when running the IF of population with aggregation

### ISSUE THREAD

**Issue by felix-yew** [inasafe/inasafe#3073] opened 2016-07-26 09:33 UTC
### Problem
I get some problems when I run with InaSAFE develop 3.5, and process the population raster data with some hazards (earthquake, flood, landslide). The process can not work properly. All of the problems is identic :

```
Details
These additional details were reported when the problem occurred.
- An exception occurred when running the impact analysis.
- 'NoneType' object has no attribute 'difference'

Diagnostics
1. In file "C:/Users/yanuaf/.qgis2/python/plugins\inasafe\safe\impact_functions\base.py", line 833, in run_analysis self._prepare()
2. In file "C:/Users/yanuaf/.qgis2/python/plugins\inasafe\safe\impact_functions\base.py", line 1036, in _prepare self.aggregator.deintersect()
3. In file "C:/Users/yanuaf/.qgis2/python/plugins\inasafe\safe\impact_statistics\aggregator.py", line 470, in deintersect self.hazard_layer)
4. In file "C:/Users/yanuaf/.qgis2/python/plugins\inasafe\safe\impact_statistics\aggregator.py", line 1359, in _prepare_polygon_layer int_com.difference(int_sym))
```

When I run the same data, but without aggregation, it can work properly and the result looks good.

### Expected Behaviour
Analysis can work properly and the result better as usually.

### Environment
* InaSAFE : develop 3.5
* QGIS : 2.14.3
* OS : Win 7 64-bit/ RAM 12 GB
* Data used :
  * Earthquake data : http://data.inasafe.org/InaSAFE%203.2%20Data/Nagekeo.zip
  * Flood data : http://data.inasafe.org/InaSAFE%203.2%20Data/DKI%20Jakarta.zip
  * Generic data : http://data.inasafe.org/InaSAFE%203.2%20Data/Nagekeo.zip

### Proposed Solution
Make it happy :smile:

**Comment by Gustry** [comment] 2016-08-01 07:03
I think it's a duplicate of #2798, I'm going to close this one. Feel free to reopen

**Closed by Gustry** 2016-08-01 07:03 UTC
